/*
 * jQuery clueTip plugin
 * Version 0.9.8  (05/22/2008)
 * @requires jQuery v1.1.4+
 * @requires Dimensions plugin (for jQuery versions < 1.2.5)
 *
 * Dual licensed under the MIT and GPL licenses:
 * http://www.opensource.org/licenses/mit-license.php
 * http://www.gnu.org/licenses/gpl.html
 *
 */
(function(E){var I,H,G,D,F,J,C;E.fn.cluetip=function(L,K){if(typeof L=="object"){K=L;L=null}return this.each(function(j){var U=E(this);var f=E.extend(false,{},E.fn.cluetip.defaults,K||{},E.metadata?U.metadata():E.meta?U.data():{});var O=false;var Y=parseInt(f.cluezIndex,10)-1;var r=false,q=0;if(!E("#cluetip").length){H=E('<div id="cluetip-inner"></div>');D=E('<h3 id="cluetip-title"></h3>');G=E('<div id="cluetip-outer"></div>').append(H).prepend(D);I=E('<div id="cluetip"></div>').css({zIndex:f.cluezIndex}).append(G).append('<div id="cluetip-extra"></div>')[B](A).hide();
E('<div id="cluetip-waitimage"></div>').css({position:"absolute",zIndex:Y-1}).insertBefore("#cluetip").hide();I.css({position:"absolute",zIndex:Y});G.css({position:"relative",zIndex:Y+1});F=E('<div id="cluetip-arrows" class="cluetip-arrows"></div>').css({zIndex:Y+1}).appendTo("#cluetip")}var h=(f.dropShadow)?+f.dropShadowSteps:0;if(!J){J=E([]);for(var u=0;u<h;u++){J=J.add(E("<div></div>").css({zIndex:Y-u-1,opacity:0.1,top:1+u,left:1+u}))}J.css({position:"absolute",backgroundColor:"#000"}).prependTo(I)
}var d=U.attr(f.attribute),R=f.cluetipClass;if(!d&&!f.splitTitle&&!L){return true}if(f.local&&f.hideLocal){E(d+":first").hide()}var e=parseInt(f.topOffset,10),a=parseInt(f.leftOffset,10);var Z,s;var W=isNaN(parseInt(f.height,10))?"auto":(/\D/g).test(f.height)?f.height:f.height+"px";var M,S,k,x,m,t;var X=isNaN(parseInt(f.width,10))?275:parseInt(f.width,10);var v=X+(parseInt(I.css("paddingLeft"))||0)+(parseInt(I.css("paddingRight"))||0)+h;var b=this.offsetWidth;var T,l,y,n,N;var p;var g=(f.attribute!="title")?U.attr(f.titleAttribute):"";
if(f.splitTitle){if(g==undefined){g=""}p=g.split(f.splitTitle);g=p.shift()}var Q;var V=function(AD){if(!f.onActivate(U)){return false}r=true;I.removeClass().css({width:X});if(d==U.attr("href")){U.css("cursor",f.cursor)}U.attr("title","");if(f.hoverClass){U.addClass(f.hoverClass)}S=k=U.offset().top;T=U.offset().left;n=AD.pageX;m=AD.pageY;if(U[0].tagName.toLowerCase()!="area"){M=E(document).scrollTop();N=E(window).width()}if(f.positionBy=="fixed"){l=b+T+a;I.css({left:l})}else{l=(b>T&&T>v)||T+b+v+a>N?T-v-a:b+T+a;
if(U[0].tagName.toLowerCase()=="area"||f.positionBy=="mouse"||b+v>N){if(n+20+v>N){I.addClass(" cluetip-"+R);l=(n-v-a)>=0?n-v-a-parseInt(I.css("marginLeft"),10)+parseInt(H.css("marginRight"),10):n-(v/2)}else{l=n+a}}var AA=l<0?AD.pageY+e:AD.pageY;I.css({left:(l>0&&f.positionBy!="bottomTop")?l:(n+(v/2)>N)?N/2-v/2:Math.max(n-(v/2),0)})}s=E(window).height();if(L){H.html(L);o(AA)}else{if(p){var AB=p.length;for(var AC=0;AC<AB;AC++){if(AC==0){H.html(p[AC])}else{H.append('<div class="split-body">'+p[AC]+"</div>")
}}o(AA)}else{if(!f.local&&d.indexOf("#")!=0){if(O&&f.ajaxCache){H.html(O);o(AA)}else{var AE=f.ajaxSettings;AE.url=d;AE.beforeSend=function(){G.children().empty();if(f.waitImage){E("#cluetip-waitimage").css({top:m+20,left:n+20}).show()}};AE.error=function(){if(r){H.html("<i>sorry, the contents could not be loaded</i>")}};AE.success=function(i){O=f.ajaxProcess(i);if(r){H.html(O)}};AE.complete=function(){C=E("#cluetip-inner img").length;if(C&&!E.browser.opera){E("#cluetip-inner img").load(function(){C--;
if(C<1){E("#cluetip-waitimage").hide();if(r){o(AA)}}})}else{E("#cluetip-waitimage").hide();if(r){o(AA)}}};E.ajax(AE)}}else{if(f.local){var AF=E(d+":first");var z=E.fn.wrapInner?AF.wrapInner("<div></div>").children().clone(true):AF.html();E.fn.wrapInner?H.empty().append(z):H.html(z);o(AA)}}}}};var o=function(AA){I.addClass("cluetip-"+R);if(f.truncate){var AB=H.text().slice(0,f.truncate)+"...";H.html(AB)}function i(){}g?D.show().html(g):(f.showTitle)?D.show().html("&nbsp;"):D.hide();if(f.sticky){var z=E('<div id="cluetip-close"><a href="#">'+f.closeText+"</a></div>");
(f.closePosition=="bottom")?z.appendTo(H):(f.closePosition=="title")?z.prependTo(D):z.prependTo(H);z.click(function(){c();return false});if(f.mouseOutClose){if(E.fn.hoverIntent&&f.hoverIntent){I.hoverIntent({over:i,timeout:f.hoverIntent.timeout,out:function(){z.trigger("click")}})}else{I.hover(i,function(){z.trigger("click")})}}else{I.unbind("mouseout")}}var AC="";G.css({overflow:W=="auto"?"visible":"auto",height:W});Z=W=="auto"?Math.max(I.outerHeight(),I.height()):parseInt(W,10);x=k;t=M+s;if(f.positionBy=="fixed"){x=k-f.dropShadowSteps+e
}else{if((l<n&&Math.max(l,0)+v>n)||f.positionBy=="bottomTop"){if(k+Z+e>t&&m-M>Z+e){x=m-Z-e;AC="top"}else{x=m+e;AC="bottom"}}else{if(k+Z+e>t){x=(Z>=s)?M:t-Z-e}else{if(U.css("display")=="block"||U[0].tagName.toLowerCase()=="area"||f.positionBy=="mouse"){x=AA-e}else{x=k-f.dropShadowSteps}}}}if(AC==""){l<T?AC="left":AC="right"}I.css({top:x+"px"}).removeClass().addClass("clue-"+AC+"-"+R).addClass(" cluetip-"+R);if(f.arrows){var AD=(k-x-f.dropShadowSteps);F.css({top:(/(left|right)/.test(AC)&&l>=0&&AD>0)?AD+"px":/(left|right)/.test(AC)?0:""}).show()
}else{F.hide()}J.hide();I.hide()[f.fx.open](f.fx.open!="show"&&f.fx.openSpeed);if(f.dropShadow){J.css({height:Z,width:X}).show()}if(E.fn.bgiframe){I.bgiframe()}if(f.delayedClose>0){q=setTimeout(c,f.delayedClose)}f.onShow(I,H)};var w=function(){r=false;E("#cluetip-waitimage").hide();if(!f.sticky||(/click|toggle/).test(f.activation)){c();clearTimeout(q)}if(f.hoverClass){U.removeClass(f.hoverClass)}E(".cluetip-clicked").removeClass("cluetip-clicked")};var c=function(){G.parent().hide().removeClass().end().children().empty();
if(g){U.attr(f.titleAttribute,g)}U.css("cursor","");if(f.arrows){F.css({top:""})}};if((/click|toggle/).test(f.activation)){U.click(function(i){if(I.is(":hidden")||!U.is(".cluetip-clicked")){V(i);E(".cluetip-clicked").removeClass("cluetip-clicked");U.addClass("cluetip-clicked")}else{w(i)}this.blur();return false})}else{if(f.activation=="focus"){U.focus(function(i){V(i)});U.blur(function(i){w(i)})}else{U.click(function(){if(U.attr("href")&&U.attr("href")==d&&!f.clickThrough){return false}});var P=function(i){if(f.tracking==true){var AA=l-i.pageX;
var z=x?x-i.pageY:k-i.pageY;U.mousemove(function(AB){I.css({left:AB.pageX+AA,top:AB.pageY+z})})}};if(E.fn.hoverIntent&&f.hoverIntent){U.mouseover(function(){U.attr("title","")}).hoverIntent({sensitivity:f.hoverIntent.sensitivity,interval:f.hoverIntent.interval,over:function(i){V(i);P(i)},timeout:f.hoverIntent.timeout,out:function(i){w(i);U.unbind("mousemove")}})}else{U.hover(function(i){V(i);P(i)},function(i){w(i);U.unbind("mousemove")})}}}})};E.fn.cluetip.defaults={width:275,height:"auto",cluezIndex:97,positionBy:"auto",topOffset:15,leftOffset:15,local:false,hideLocal:true,attribute:"rel",titleAttribute:"title",splitTitle:"",showTitle:true,cluetipClass:"default",hoverClass:"",waitImage:true,cursor:"help",arrows:false,dropShadow:true,dropShadowSteps:6,sticky:false,mouseOutClose:false,activation:"hover",clickThrough:false,tracking:false,delayedClose:0,closePosition:"top",closeText:"Close",truncate:0,fx:{open:"show",openSpeed:""},hoverIntent:{sensitivity:3,interval:50,timeout:0},onActivate:function(K){return true
},onShow:function(K,L){},ajaxCache:true,ajaxProcess:function(K){K=K.replace(/<s(cript|tyle)(.|\s)*?\/s(cript|tyle)>/g,"").replace(/<(link|title)(.|\s)*?\/(link|title)>/g,"");return K},ajaxSettings:{dataType:"html"},debug:false};var B="appendTo",A="body";E.cluetip={};E.cluetip.setup=function(K){if(K&&K.insertionType&&(K.insertionType).match(/appendTo|prependTo|insertBefore|insertAfter/)){B=K.insertionType}if(K&&K.insertionElement){A=K.insertionElement}}})(jQuery);
