/* Variables header for application - AppBuilder 2.01  */

/* 'base' Window link */
const int ABN_base = 0;
const int ABN_base_File = 1;
const int ABN_base_Help = 2;

/* 'AboutDlg' Dialog link */
const int ABN_AboutDlg = 3;
const int ABN_About_Version = 4;
const int ABN_AboutDone = 5;

/* 'NewWindow' Window link */
const int ABN_NewWindow = 6;
const int ABN_ButtonPrevious = 7;
const int ABN_ButtonBlue = 8;
const int ABN_ButtonRed = 9;
const int ABN_ButtonGreen = 10;
const int ABN_ColorRect = 11;

/* 'FileMenu' Menu link */
const int ABN_FileMenu = 12;
const int ABN_File_New = 13;
const int ABN_File_Save = 14;
const int ABN_File_Save_As = 15;
const int ABN_File_Quit = 17;

/* 'HelpMenu' Menu link */
const int ABN_HelpMenu = 18;
const int ABN_Help_About = 19;

