/* Variables header for application - AppBuilder 2.01  */

/* 'base' Window link */
const int ABN_base = 0;
const int ABN_base_File = 1;
const int ABN_base_Help = 2;

/* 'FileMenu' Menu link */
const int ABN_FileMenu = 3;
const int ABN_File_New = 4;
const int ABN_File_Save = 5;
const int ABN_File_Save_As = 6;
const int ABN_File_Quit = 8;

/* 'HelpMenu' Menu link */
const int ABN_HelpMenu = 9;
const int ABN_Help_About = 10;

