/* Variables header for application - AppBuilder 2.01  */

/* 'base' Window link */
const int ABN_base = 0;
const int ABN_base_File = 1;
const int ABN_base_Help = 2;

/* 'AboutDlg' Dialog link */
const int ABN_AboutDlg = 3;
const int ABN_About_Version = 4;
const int ABN_AboutDone = 5;

/* 'FileMenu' Menu link */
const int ABN_FileMenu = 6;
const int ABN_File_New = 7;
const int ABN_File_Save = 8;
const int ABN_File_Save_As = 9;
const int ABN_File_Quit = 11;

/* 'HelpMenu' Menu link */
const int ABN_HelpMenu = 12;
const int ABN_Help_About = 13;

