/* JS */ gapi.loaded_0(function(_){var window=this;
_.m=function(a){throw a;};_.p=void 0;_.r=!0;_.s=null;_.u=!1;_.aa=function(){return function(a){return a}};_.v=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.y=function(a){return function(){return this[a]}};_.ca=function(a){return function(){return a}};_.C=function(a,c,f){a=a.split(".");f=f||_.D;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.F)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};
_.da=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.F=function(a){return a!==_.p};_.fa=function(a){return"array"==(0,_.da)(a)};_.ga=function(a){var c=(0,_.da)(a);return"array"==c||"object"==c&&"number"==typeof a.length};_.ha=function(a){return"string"==typeof a};_.ia=function(a){return"function"==(0,_.da)(a)};_.ja=function(a){var c=typeof a;return"object"==c&&a!=_.s||"function"==c};_.ka=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.la=function(a,c,f){a||(0,_.m)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.G=function(a,c,f){_.G=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.ka:_.la;return _.G.apply(_.s,arguments)};
_.ma=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_._DumpException=function(a){(0,_.m)(a)};_.na=_.na||{};_.D=this;_.oa="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.pa=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.G.apply(_.s,f)}return(0,_.G)(this,a)};
_.ra=window.gapi||{};_.ta=window.gadgets||{};_.H=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.u},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"}},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.r,"pos.plusones.list":_.r,"pos.plusones.get":_.r,"chili.people.get":_.r,"pos.plusones.insert":_.r,"chili.activities.list":_.r,"pos.plusones.delete":_.r,"chili.activities.get":_.r,
"chili.activities.search":_.r,"pos.plusones.getSignupState":_.r},requestCache:{enabled:_.r},versions:{chili:"v1",pos:"v1"},rpc:"/rpc",root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.r},transport:{isProxyShared:_.r},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.u}},drive_saver:{driveUrl:"https://drive.google.com"}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"}});
_.I=function(a,c,f){return a[c]=a[c]||f};_.va=function(a){return"function"===typeof a};_.wa=function(a){return(0,window.String)(a).replace(_.xa,"&amp;").replace(_.ya,"&lt;").replace(_.za,"&gt;").replace(_.Aa,"&quot;").replace(_.Ba,"&#39;")};_.L=function(){var a;if((a=window.Object.create)&&_.Ca.test(a))a=a(_.s);else{a={};for(var c in a)a[c]=_.p}return a};_.Da=function(a,c){return window.Object.prototype.hasOwnProperty.call(a,c)};_.Ea=function(a,c){a=a||{};for(var f in a)(0,_.Da)(a,f)&&(c[f]=a[f])};
_.Fa=function(a,c){a||(0,_.m)((0,window.Error)(c||""))};_.Ga=function(a,c,f){var g=(0,window.RegExp)("([#].*&|[#])"+c+"=([^&#]*)","g");c=(0,window.RegExp)("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};_.Ha=function(a){a=a.match(_.Ia);var c=(0,_.L)();c.uc=a[1];c.jb=a[3]?[a[3]]:[];c.Lf=a[5]?[a[5]]:[];return c};
_.Ja=function(a){a=a?a.split("&"):[];for(var c=[],f=0;f<a.length;f++){var g=a[f].split("=",2);c.push([(0,window.decodeURIComponent)(g[0]),(0,window.decodeURIComponent)(g[1])])}return c};_.Ka=function(a){return a.uc+(0<a.jb.length?"?"+a.jb.join("&"):"")+(0<a.Lf.length?"#"+a.Lf.join("&"):"")};_.La=function(a){var c=[];if(a)for(var f in a)(0,_.Da)(a,f)&&a[f]!=_.s&&c.push((0,window.encodeURIComponent)(f)+"="+(0,window.encodeURIComponent)(a[f]));return c};
_.Ma=function(a,c,f){a=(0,_.Ha)(a);a.jb.push.apply(a.jb,(0,_.La)(c));a.Lf.push.apply(a.Lf,(0,_.La)(f));return(0,_.Ka)(a)};_.Na=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.Oa=function(a){return!_.Pa.dpo?(0,_.Ga)(a,"jsh",_.Pa.h):_.Pa.h};_.Qa=function(a){return(0,_.Ga)(a,"_bsh",_.Pa.bsh)};_.Ra=function(){return(0,_.I)(_.Pa,"WI",(0,_.L)())};_.Sa=function(){return _.Pa.onl};_.Ta=function(a){_.Pa.onl=a};_.Ua=function(a){var c=window.___jsl=window.___jsl||{};c[a]=c[a]||[];return c[a]};
_.Va=function(a){var c=window.___jsl=window.___jsl||{};c.cfg=!a&&c.cfg||{};return c.cfg};_.Wa=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};_.Xa=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.Wa)(a[f])&&!(0,_.Wa)(c[f])?(0,_.Xa)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.Wa)(c[f])?[]:{},(0,_.Xa)(a[f],c[f])):a[f]=c[f])};
_.Ya=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var c;try{c=window.JSON.parse(a)}catch(f){}if("object"===typeof c)return c;try{c=(new window.Function("return ("+a+"\n)"))()}catch(g){}if("object"===typeof c)return c;try{c=(new window.Function("return ({"+a+"\n})"))()}catch(h){}return"object"===typeof c?c:{}}};
_.Za=function(a){(0,_.Va)(_.r);var c=window.___gcfg,f=(0,_.Ua)("cu");if(c&&c!==window.___gu){var g={};(0,_.Xa)(g,c);f.push(g);window.___gu=c}var c=(0,_.Ua)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],l=[];l.push.apply(l,(0,_.I)(_.Pa,"us",[]));for(var n=0;n<h.length;++n)for(var q=h[n],t=0;t<l.length;++t)q.src&&0==q.src.indexOf(l[t])&&g.push(q);0==g.length&&(0<h.length&&h[h.length-1].src)&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)g[h].getAttribute("gapi_processed")||
(g[h].setAttribute("gapi_processed",_.r),(l=g[h])?(n=l.nodeType,l=3==n||4==n?l.nodeValue:l.textContent||l.innerText||l.innerHTML||""):l=_.p,(l=(0,_.Ya)(l))&&c.push(l));a&&(g={},(0,_.Xa)(g,a),f.push(g));g=(0,_.Ua)("cd");a=0;for(c=g.length;a<c;++a)(0,_.Xa)((0,_.Va)(),g[a]);g=(0,_.Ua)("ci");a=0;for(c=g.length;a<c;++a)(0,_.Xa)((0,_.Va)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.Xa)((0,_.Va)(),f[a])};
_.N=function(a,c){if(!a)return(0,_.Va)();for(var f=a.split("/"),g=(0,_.Va)(),h=0,l=f.length;g&&"object"===typeof g&&h<l;++h)g=g[f[h]];return h===f.length&&g!==_.p?g:c};_.$a=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),l=0,n=h.length;l<n-1;++l)var q={},g=g[h[l]]=q;g[h[l]]=c}(0,_.Za)(f)};_.ab=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.I)(_.Pa,"ci",[]).push(a),window.__GOOGLEAPIS=_.p)}; _.O=function(a,c){c="function"==typeof _.bb&&(0,_.bb)(a,c)||c;(0,_.C)(a,c,_.p)};
_.cb=window;_.db=window.document;_.Ca=/\[native code\]/;_.xa=/&/g;_.ya=/</g;_.za=/>/g;_.Aa=/"/g;_.Ba=/'/g;_.eb=(0,_.I)(_.cb,"gapi",{});_.Ia=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.Pa=(0,_.I)(_.cb,"___jsl",(0,_.L)());(0,_.I)(_.Pa,"I",0);(0,_.I)(_.Pa,"hel",10);_.ab&&(0,_.ab)();(0,_.Za)();(0,_.O)("gapi.config.get",_.N);(0,_.O)("gapi.config.update",_.$a);


_.kb={go:{},I:{}};_.lb={go:{},I:{}};


_.Q=_.Q||{};
_.Q=_.Q||{};_.Q.sg=function(a,c,f){for(var g=[],h=2,l=arguments.length;h<l;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,l=arguments.length;h<l;++h)f.push(arguments[h]);return c.apply(a,f)}};_.Q.ff=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

_.tb=function(a,c){return window.String.fromCharCode(c)};_.Q=_.Q||{};_.ub={"0":_.u,10:_.r,13:_.r,34:_.r,39:_.r,60:_.r,62:_.r,92:_.r,8232:_.r,8233:_.r,65282:_.r,65287:_.r,65308:_.r,65310:_.r,65340:_.r};_.Q.escape=function(a,c){if(a){if("string"===typeof a)return _.Q.If(a);if("array"===typeof a)for(var f=0,g=a.length;f<g;++f)a[f]=_.Q.escape(a[f]);else if("object"===typeof a&&c){f={};for(g in a)a.hasOwnProperty(g)&&(f[_.Q.If(g)]=_.Q.escape(a[g],_.r));return f}}return a}; _.Q.If=function(a){if(!a)return a;for(var c=[],f,g,h=0,l=a.length;h<l;++h)f=a.charCodeAt(h),g=_.ub[f],g===_.r?c.push("&#",f,";"):g!==_.u&&c.push(a.charAt(h));return c.join("")};_.Q.pv=function(a){return!a?a:a.replace(/&#([0-9]+);/g,_.tb)};

_.xb=_.xb||{};_.xb.Ip=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

_.yb=function(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)};_.xb=_.xb||{};
_.xb.Gh=function(){var a=_.xb.Ip().height,c=window.document.body,f=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&f.scrollHeight)return f.scrollHeight!==a?f.scrollHeight:f.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){a=0;for(c=[window.document.body];0<c.length;){var g=c.shift(),f=g.childNodes;if("undefined"!==typeof g.style){var h=g.style.overflowY;h||(h=(h=window.document.defaultView.getComputedStyle(g,_.s))?h.overflowY:_.s);if("visible"!=h&&
"inherit"!=h&&(h=g.style.height,h||(h=(h=window.document.defaultView.getComputedStyle(g,_.s))?h.height:""),0<h.length&&"auto"!=h))continue}for(g=0;g<f.length;g++){h=f[g];if("undefined"!==typeof h.offsetTop&&"undefined"!==typeof h.offsetHeight)var l=h.offsetTop+h.offsetHeight+(0,_.yb)(h,"margin-bottom"),a=window.Math.max(a,l);c.push(h)}}return a+(0,_.yb)(window.document.body,"border-bottom")+(0,_.yb)(window.document.body,"margin-bottom")+(0,_.yb)(window.document.body,"padding-bottom")}if(c&&f)return g= f.scrollHeight,h=f.offsetHeight,f.clientHeight!==h&&(g=c.scrollHeight,h=c.offsetHeight),g>a?g>h?g:h:g<h?g:h};

_.Tc=window.gapi&&window.gapi.util||{};
_.Uc=_.Tc=_.Tc||{};_.Vc={rj:"bsh",uj:"h"};window.___jsl=window.___jsl||{};_.Uc.eh={b:function(){return window.___jsl[_.Vc.rj]},fk:function(){return window.___jsl[_.Vc.uj]},Ui:function(a){window.___jsl[_.Vc.rj]=a},Ur:function(a){window.___jsl[_.Vc.uj]=a}};

if(window.JSON&&window.JSON.parse&&window.JSON.stringify){_.mb=function(a){return this[a]};_.nb=/___$/;_.P={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.u}},stringify:function(a){function c(a){return f.call(this,a,_.mb)}var f=window.JSON.stringify,g=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===f([{x:1}])?c:f;try{return g(a,function(a,c){return!_.nb.test(a)?c:_.p})}catch(h){return _.s}}}};
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.P=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,l,n;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){n=a.length;for(l=0;l<n;l+=1)h.push(c(a[l])||"null");return"["+h.join(",")+"]"}for(l in a)!/___$/.test(l)&&a.hasOwnProperty(l)&&"string"===typeof l&&(n=c(a[l]))&&h.push(c(l)+":"+n);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.u}}}();
_.P.Zj=function(a){var c={};if(a===_.s||a===_.p)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.s===g||_.p===g||(c[f]="string"===typeof g?g:_.P.stringify(g))}return c};(0,_.O)("gadgets.json.flatten",_.P.Zj);(0,_.O)("gadgets.json.parse",_.P.parse);(0,_.O)("gadgets.json.stringify",_.P.stringify);(0,_.O)("gadgets.json.flatten",_.P.Zj);(0,_.O)("gadgets.json.parse",_.P.parse);(0,_.O)("gadgets.json.stringify",_.P.stringify);

_.Q=_.Q||{};_.zb=[];_.Q.ev=function(a){_.zb.push(a)};_.Q.jv=function(){for(var a=0,c=_.zb.length;a<c;++a)_.zb[a]()};
_.vb=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.Q=_.Q||{};_.wb=_.s;
_.Q.na=function(a){var c="undefined"===typeof a;if(_.wb!==_.s&&c)return _.wb;var f={};a=a||window.document.location.href;var g=a.indexOf("?"),h=a.indexOf("#");a=(-1===h?a.substr(g+1):[a.substr(g+1,h-g-1),"&",a.substr(h+1)].join("")).split("&");for(var g=window.decodeURIComponent?window.decodeURIComponent:window.unescape,h=0,l=a.length;h<l;++h){var n=a[h].indexOf("=");if(-1!==n){var q=a[h].substring(0,n),n=a[h].substring(n+1),n=n.replace(/\+/g," ");try{f[q]=g(n)}catch(t){}}}c&&(_.wb=f);return f};_.Q.na();
(0,_.O)("gadgets.util.getUrlParameters",_.Q.na);
_.Bb=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;_.Bb&&(0,_.$a)((0,_.Bb)());_.Ab={N:function(a,c,f){f&&f((0,_.N)())},get:function(a){return(0,_.N)(a)},update:function(a,c){c&&(0,_.m)("Config replacement is not supported");(0,_.$a)(a)},ea:(0,_.v)()};
(0,_.O)("gadgets.config.register",_.Ab.N);(0,_.O)("gadgets.config.get",_.Ab.get);(0,_.O)("gadgets.config.init",_.Ab.ea);(0,_.O)("gadgets.config.update",_.Ab.update);
_.Cb=_.Cb||{};_.Cb.Vl=_.s;_.Cb.sl=_.s;_.Cb.hg=_.s;_.Cb.frameElement=_.s;_.Cb=_.Cb||{};
if(!_.Cb.oj){_.Fb=function(a){var c=_.P.parse(a.data);if(c&&c.f){var f=_.R.Wd(c.f);(!_.Db||!("undefined"!==typeof a.origin?a.origin!==f:a.domain!==/^.+:\/\/([^:]+).*/.exec(f)[1]))&&(0,_.Eb)(c,a.origin)}};_.Db=_.r;_.Cb.oj={dk:(0,_.ca)("wpm"),b:(0,_.ca)(_.r),ea:function(a,c){_.Ab.N("rpc",_.s,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))_.Db=_.u});_.Eb=a;_.Gb=c;"undefined"!=typeof window.addEventListener?window.addEventListener("message",_.Fb,_.u):"undefined"!=typeof window.attachEvent&&
window.attachEvent("onmessage",_.Fb);window.___jsl=window.___jsl||{};var f=window.___jsl;f.RPMQ=f.RPMQ||[];f.RPMQ.push(_.Fb);(0,_.Gb)("..",_.r);return _.r},Zc:function(a){(0,_.Gb)(a,_.r);return _.r},call:function(a,c,f){var g=_.R.Wd(a),h=_.R.Cj(a);g?window.setTimeout(function(){h.postMessage(_.P.stringify(f),g)},0):".."!=a&&(0,_.ua)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message");return _.r}}};
_.Cb=_.Cb||{};
if(!_.Cb.Kf){_.Hb=_.Cb;_.Kb=function(a,c){function f(){a.apply({},arguments)}_.Ib[c]=_.Ib[c]||f;return _.Jb+"."+c};_.Rb=function(){if(_.Lb===_.s&&window.document.body&&_.Mb){var a=_.Mb+"?cb="+window.Math.random()+"&origin="+_.Nb+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+_.Ob+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+
a+'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;_.Lb=c.firstChild}++_.Pb;_.Qb!==_.s&&(_.Lb!==_.s||50<=_.Pb)?window.clearTimeout(_.Qb):_.Qb=window.setTimeout(_.Rb,100)};_.Yb=function(){_.Sb[".."]||((0,_.Vb)(".."),_.Wb++,50<=_.Wb&&_.Xb!==_.s?(window.clearTimeout(_.Xb),_.Xb=_.s):_.Xb=window.setTimeout(_.Yb,100))};_.$b=function(){if(_.Lb!==_.s&&_.Lb.setup)for(;0<_.Zb.length;){var a=_.Zb.shift(),c=a.ls;_.Lb.setup(a.pe,".."===c?_.R.Vg:c,".."===c?"INNER":"OUTER")}_.Qb!==
_.s&&window.clearTimeout(_.Qb);_.Qb=_.s};_.ac=function(){!_.Sb[".."]&&_.Xb===_.s&&(_.Xb=window.setTimeout(_.Yb,100))};_.bc=function(a,c,f){c=_.R.Wd(a);var g=_.R.Sd(a);_.Lb["sendMessage_"+(".."===a?_.R.Vg:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(_.Lb,_.P.stringify(f),c);return _.r};_.ec=function(a,c){var f=_.P.parse(a),g=f._scr;g?((0,_.cc)(g,_.r),_.Sb[g]=_.r,".."!==g&&(0,_.Vb)(g,_.r)):window.setTimeout(function(){(0,_.dc)(f,c)},0)};_.Vb=function(a,c){var f=_.R.Vg,g={};g._scr=c?"..":f;g._pnt=f;
(0,_.bc)(a,f,g)};_.Ob="___xpcswf";_.Mb=_.s;_.fc=_.u;_.dc=_.s;_.cc=_.s;_.Lb=_.s;_.Zb=[];_.Qb=_.s;_.Pb=0;_.Wb=0;_.Xb=_.s;_.Sb={};_.Nb=window.location.protocol+"//"+window.location.host;window.___jsl=window.___jsl||{};_.gc=window.___jsl._fm={};_.Jb="___jsl._fm";_.Ib=_.gc;_.Ab.N("rpc",_.s,function(a){_.fc&&(_.Mb=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});(0,_.Kb)(_.$b,"ready");(0,_.Kb)(_.ac,"setupDone");(0,_.Kb)(_.ec,"receiveMessage");_.Hb.Kf={dk:(0,_.ca)("flash"),b:(0,_.ca)(_.r), ea:function(a,c){_.dc=a;_.cc=c;return _.fc=_.r},Zc:function(a,c){_.Zb.push({pe:c,ls:a});_.Lb===_.s&&_.Qb===_.s&&(_.Qb=window.setTimeout(_.Rb,100));return _.r},call:_.bc,lo:_.ec,d:_.$b,i:_.ac}};
if(!window.gadgets||!window.gadgets.rpc){_.oc=function(a,c){if(!_.hc[a]){var f=_.ic;c||(f=_.jc);_.hc[a]=f;for(var g=_.mc[a]||[],h=0;h<g.length;++h){var l=g[h];l.t=_.nc[a];f.call(a,l.f,l)}_.mc[a]=[]}};_.tc=function(a,c,f,g,h){function l(){_.pc=_.r}if(!_.nc[c]||_.nc[c]!==f)(0,_.ua)("Invalid gadgets.rpc token. "+_.nc[c]+" vs "+f),(0,_.qc)(c,2);h.onunload=function(){_.rc[c]&&!_.pc&&((0,_.qc)(c,1),_.R.Si(c))};_.sc||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",l,_.u):"undefined"!=
typeof window.attachEvent&&window.attachEvent("onunload",l),_.sc=_.r);g=_.P.parse((0,window.decodeURIComponent)(g))};_.wc=function(a,c){if(a&&"string"===typeof a.s&&"string"===typeof a.f&&a.a instanceof window.Array)if(_.nc[a.f]&&_.nc[a.f]!==a.t&&((0,_.ua)("Invalid gadgets.rpc token. "+_.nc[a.f]+" vs "+a.t),(0,_.qc)(a.f,2)),"__ack"===a.s)window.setTimeout(function(){(0,_.oc)(a.f,_.r)},0);else{a.c&&(a.callback=function(c){_.R.call(a.f,(a.g?"legacy__":"")+"__cb",_.s,a.c,c)});if(c){var f=(0,_.uc)(c);
a.origin=c;var g=a.r;if(!g||(0,_.uc)(g)!=f)g=c;a.referer=g}f=(_.vc[a.s]||_.vc[""]).apply(a,a.a);a.c&&"undefined"!==typeof f&&_.R.call(a.f,"__cb",_.s,a.c,f)}};_.uc=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));var f="",g=c.indexOf(":");if(-1!=g){var h=
c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};_.xc=function(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.s}}return _.s};_.yc=function(a){if("undefined"===typeof a||".."===a)return window.parent;var c=(0,_.xc)(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:
_.s};_.zc=function(a,c){if(_.rc[a]!==_.r){"undefined"===typeof _.rc[a]&&(_.rc[a]=0);var f=(0,_.yc)(a);(".."===a||f!=_.s)&&_.ic.Zc(a,c)===_.r?_.rc[a]=_.r:_.rc[a]!==_.r&&10>_.rc[a]++?window.setTimeout(function(){(0,_.zc)(a,c)},500):(_.hc[a]=_.jc,_.rc[a]=_.r)}};_.Bc=function(a){(a=_.Ac[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a};_.Ec=function(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));_.Ac[a]=c;"undefined"!==typeof f&&(_.Dc[a]=!!f)};_.Fc=function(a,c){c=c||"";_.nc[a]=(0,window.String)(c);(0,_.zc)(a,c)};_.Ic=function(a){a=(a.passReferrer||"").split(":",2);_.Gc=a[0]||"none";_.Hc=a[1]||"origin"};_.Jc=function(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(_.ic=_.Cb.hg||_.jc,_.ic.ea(_.wc,_.oc))};_.Lc=
function(a,c,f){if(".."===a){var g=f||_.Kc.rpctoken||_.Kc.ifpctok||"";a=function(a){a=a&&a.rpc||{};(0,_.Ic)(a);var f=a.parentRelayUrl||"",f=(0,_.uc)(_.Kc.parent||c)+f;(0,_.Ec)("..",f,"true"===(0,window.String)(a.useLegacyProtocol));(0,_.Jc)(a);(0,_.Fc)("..",g)};!_.Kc.parent&&c?a({}):_.Ab.N("rpc",_.s,a)}else a:{var h=_.s;if("/"!=a.charAt(0)){if(!_.Q)break a;(h=window.document.getElementById(a))||(0,_.m)((0,window.Error)("h`"+a))}var h=h&&h.src,l=c||_.R.ja(h);(0,_.Ec)(a,l);h=_.Q.na(h);(0,_.Fc)(a,f||
h.rpctoken)}};_.vc={};_.Ac={};_.Dc={};_.nc={};_.Mc=0;_.Nc={};_.rc={};_.Kc={};_.hc={};_.mc={};_.Gc=_.s;_.Hc=_.s;_.Oc=window.top!==window.self;_.Pc=window.name;_.qc=(0,_.v)();_.Qc=window.console;_.Rc=_.Qc&&_.Qc.log&&function(a){_.Qc.log(a)}||(0,_.v)();_.Sc=function(a){return function(){(0,_.Rc)(a+": call ignored")}};_.jc={getCode:(0,_.ca)("noop"),isParentVerifiable:(0,_.ca)(_.r),init:(0,_.Sc)("init"),setup:(0,_.Sc)("setup"),call:(0,_.Sc)("call")};_.Q&&(_.Kc=_.Q.na());_.pc=_.u;_.sc=_.u;_.ic=function(){if("flash"==
_.Kc.rpctx)return _.Cb.Kf;if("rmr"==_.Kc.rpctx)return _.Cb.Vl;var a="function"===typeof window.postMessage?_.Cb.oj:"object"===typeof window.postMessage?_.Cb.oj:window.ActiveXObject?_.Cb.Kf?_.Cb.Kf:_.Cb.sl?_.Cb.sl:_.Cb.hg:0<window.navigator.userAgent.indexOf("WebKit")?_.Cb.Vl:"Gecko"===window.navigator.product?_.Cb.frameElement:_.Cb.hg;a||(a=_.jc);return a}();_.vc[""]=function(){(0,_.Rc)("Unknown RPC service: "+this.s)};_.vc.__cb=function(a,c){var f=_.Nc[a];f&&(delete _.Nc[a],f.call(this,c))};_.R=
{Da:function(a){"function"===typeof a.Fr&&(_.qc=a.Fr)},N:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("i"));""===a&&(0,_.m)((0,window.Error)("j"));_.vc[a]=c},Vb:function(a){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("k"));""===a&&(0,_.m)((0,window.Error)("l"));delete _.vc[a]},Ml:function(a){_.vc[""]=a},ym:function(){delete _.vc[""]},bk:(0,_.v)(),call:function(a,c,f,g){a=a||"..";var h="..";".."===a?h=_.Pc:"/"==a.charAt(0)&&(h=_.R.ja(window.location.href),h="/"+_.Pc+(h?
"|"+h:""));++_.Mc;f&&(_.Nc[_.Mc]=f);var l={s:c,f:h,c:f?_.Mc:0,a:window.Array.prototype.slice.call(arguments,3),t:_.nc[a],l:!!_.Dc[a]},n;a:if("bidir"===_.Gc||"c2p"===_.Gc&&".."===a||"p2c"===_.Gc&&".."!==a){n=window.location.href;var q="?";if("query"===_.Hc)q="#";else if("hash"===_.Hc)break a;q=n.lastIndexOf(q);q=-1===q?n.length:q;n=n.substring(0,q)}else n=_.s;n&&(l.r=n);".."!==a&&(0,_.xc)(a)==_.s&&!window.document.getElementById(a)||(n=_.hc[a],!n&&(0,_.xc)(a)!==_.s&&(n=_.ic),0===c.indexOf("legacy__")&&
(n=_.ic,l.s=c.substring(8),l.c=l.c?l.c:_.Mc),l.g=_.r,l.r=h,n?(_.Dc[a]&&(n=_.Cb.hg),n.call(a,h,l)===_.u&&(_.hc[a]=_.jc,_.ic.call(a,h,l))):_.mc[a]?_.mc[a].push(l):_.mc[a]=[l])},ik:_.Bc,Lg:_.Ec,Kg:_.Fc,kf:_.Lc,Sd:function(a){return _.nc[a]},Si:function(a){delete _.Ac[a];delete _.Dc[a];delete _.nc[a];delete _.rc[a];delete _.hc[a]},hk:function(){return _.ic.dk()},Kl:function(a,c){4<a.length?_.ic.lo(a,_.wc):_.tc.apply(_.s,a.concat(c))},Ll:function(a){a.a=window.Array.prototype.slice.call(a.a);window.setTimeout(function(){(0,_.wc)(a)},
0)},ja:_.uc,Wd:function(a){var c=_.s,c=(0,_.Bc)(a);c||(c=(c=(0,_.xc)(a))?c.origin:".."==a?_.Kc.parent:window.document.getElementById(a).src);return(0,_.uc)(c)},ea:function(){_.ic.ea(_.wc,_.oc)===_.u&&(_.ic=_.jc);_.Oc?(0,_.Lc)(".."):_.Ab.N("rpc",_.s,function(a){a=a.rpc||{};(0,_.Ic)(a);(0,_.Jc)(a)})},Cj:_.yc,ko:_.xc,b:"__ack",Vg:_.Pc||"..",j:0,i:1,d:2};_.R.ea()}else if("undefined"==typeof _.R||!_.R)_.R=window.gadgets.rpc,_.R.Da=_.R.config,_.R.N=_.R.register,_.R.Vb=_.R.unregister,_.R.Ml=_.R.registerDefault,
_.R.ym=_.R.unregisterDefault,_.R.bk=_.R.forceParentVerifiable,_.R.call=_.R.call,_.R.ik=_.R.getRelayUrl,_.R.Lg=_.R.setRelayUrl,_.R.Kg=_.R.setAuthToken,_.R.kf=_.R.setupReceiver,_.R.Sd=_.R.getAuthToken,_.R.Si=_.R.removeReceiver,_.R.hk=_.R.getRelayChannel,_.R.Kl=_.R.receive,_.R.Ll=_.R.receiveSameDomain,_.R.ja=_.R.getOrigin,_.R.Wd=_.R.getTargetOrigin,_.R.Cj=_.R._getTargetWin,_.R.ko=_.R._parseSiblingId;
(0,_.O)("gadgets.rpc.config",_.R.Da);(0,_.O)("gadgets.rpc.register",_.R.N);(0,_.O)("gadgets.rpc.unregister",_.R.Vb);(0,_.O)("gadgets.rpc.registerDefault",_.R.Ml);(0,_.O)("gadgets.rpc.unregisterDefault",_.R.ym);(0,_.O)("gadgets.rpc.forceParentVerifiable",_.R.bk);(0,_.O)("gadgets.rpc.call",_.R.call);(0,_.O)("gadgets.rpc.getRelayUrl",_.R.ik);(0,_.O)("gadgets.rpc.setRelayUrl",_.R.Lg);(0,_.O)("gadgets.rpc.setAuthToken",_.R.Kg);(0,_.O)("gadgets.rpc.setupReceiver",_.R.kf);
(0,_.O)("gadgets.rpc.getAuthToken",_.R.Sd);(0,_.O)("gadgets.rpc.removeReceiver",_.R.Si);(0,_.O)("gadgets.rpc.getRelayChannel",_.R.hk);(0,_.O)("gadgets.rpc.receive",_.R.Kl);(0,_.O)("gadgets.rpc.receiveSameDomain",_.R.Ll);(0,_.O)("gadgets.rpc.getOrigin",_.R.ja);(0,_.O)("gadgets.rpc.getTargetOrigin",_.R.Wd);

_.ob=function(a,c){if(!(a<_.pb)&&_._console$$inline_295)if(2===a&&_._console$$inline_295.warn)_._console$$inline_295.warn(c);else if(3===a&&_._console$$inline_295.error)try{_._console$$inline_295.error(c)}catch(f){}else _._console$$inline_295.log&&_._console$$inline_295.log(c)};_.rb=function(a){(0,_.ob)(1,a)};_.sb=function(a){(0,_.ob)(2,a)};_.ua=function(a){(0,_.ob)(3,a)};_.rb.INFO=1;_.rb.WARNING=2;_.rb.NONE=4;_.pb=1; _._console$$inline_295=window.console?window.console:window.opera?window.opera.postError:_.p;

_.Q=_.Q||{};_.Q.xe=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.sb)("cannot attachBrowserEvent: "+c)};_.Q.nr=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.sb)("cannot removeBrowserEvent: "+c)};

_.Xc=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;x=w=0}function c(a){for(var c=n,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;a=h[0];for(var g=h[1],l=h[2],q=h[3],t=h[4],w,x,f=0;80>f;f++)40>f?20>f?(w=q^g&(l^q),x=1518500249):(w=g^l^q,x=1859775393):60>f?(w=g&l|q&(g|l),x=2400959708):(w=g^l^q,x=3395469782),w=((a<<5|a>>>27)&4294967295)+
w+t+x+c[f]&4294967295,t=q,q=l,l=(g<<30|g>>>2)&4294967295,g=a,a=w;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+l&4294967295;h[3]=h[3]+q&4294967295;h[4]=h[4]+t&4294967295}function f(a,f){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var g=[],h=0,n=a.length;h<n;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==w)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,x+=64;for(;g<f;)if(l[w++]=a[g++],x++,64==w){w=0;for(c(l);g+64<f;)c(a.slice(g,g+64)),g+=64,x+=64}}
function g(){var a=[],g=8*x;56>w?f(q,56-w):f(q,64-(w-56));for(var n=63;56<=n;n--)l[n]=g&255,g>>>=8;c(l);for(n=g=0;5>n;n++)for(var t=24;0<=t;t-=8)a[g++]=h[n]>>t&255;return a}for(var h=[],l=[],n=[],q=[128],t=1;64>t;++t)q[t]=0;var w,x;a();return{reset:a,update:f,Mu:g,Gf:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};

_.Yc=function(a){if("complete"===_.db.readyState)a();else{var c=_.u,f=function(){if(!c)return c=_.r,a.apply(this,arguments)};_.cb.addEventListener?(_.cb.addEventListener("load",f,_.u),_.cb.addEventListener("DOMContentLoaded",f,_.u)):_.cb.attachEvent&&(_.cb.attachEvent("onreadystatechange",function(){"complete"===_.db.readyState&&f.apply(this,arguments)}),_.cb.attachEvent("onload",f))}};_.$c=function(a){var c=(0,_.Xc)();c.update(a);return c.Gf()};_.ad=window.crypto;
if(_.ad&&"function"==typeof _.ad.getRandomValues)_.Zc=function(){var a=new window.Uint32Array(1);_.ad.getRandomValues(a);return(0,window.Number)("0."+a[0])};else{_.bd=(0,_.N)("random/maxObserveMousemove");_.bd==_.s&&(_.bd=-1);_.cd=0;_.dd=window.Math.random();_.ed=1;_.fd=1E6*(window.screen.width*window.screen.width+window.screen.height);_.gd=function(a){a=a||window.event;var c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.ed=_.ed*c%_.fd;0<_.bd&&++_.cd==_.bd&&
_.Q.nr(window,"mousemove",_.gd,_.u)};0!=_.bd&&_.Q.xe(window,"mousemove",_.gd,_.u);_.hd=(0,_.$c)(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+_.dd);_.Zc=function(){var a=_.ed,a=a+(0,window.parseInt)(_.hd.substr(0,20),16);_.hd=(0,_.$c)(_.hd);return a/(_.fd+window.Math.pow(16,20))}};
(0,_.O)("shindig.random",_.Zc);
_.Wc=window.iframer=window.iframer||{};_.S=window.iframes=window.iframes||{};
_.S.yo=function(a,c,f){var g=window.Array.prototype.slice.call(arguments);_.S.gk(function(a){a.sameOrigin&&(g.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.R.call.apply(_.R,g))})};_.S.kr=function(a,c){_.R.N(a,c)};

_.id=function(a){var c=(0,_.N)("googleapis.config/sessionIndex");c==_.s&&(c=window.__X_GOOG_AUTHUSER);if(c==_.s){var f=window.google;f&&(c=f.authuser)}c==_.s&&(a==_.s&&(a=window.location.href),c=a?(0,_.Ga)(a,"authuser")||_.s:_.s);return c==_.s?_.s:(0,window.String)(c)};
_.jd=function(a,c,f){a=(0,window.String)(a);if(((0,_.Ga)(a,"authuser")||_.s)!=_.s||((0,_.Ga)(a,"hd")||_.s)!=_.s)return a;c=(0,_.id)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var l=h[1],n=h[4],q=h[5];h[3]=="/"+f&&(g=(l||"")+(n||"/")+(q||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return l=h[2],a=h[4]||h[5],q=h[6],c!=_.s&&(g=(l||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+
(q||"")),g}f=c==_.s?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.kd=_.jd;
_.ld=function(){var a=(0,_.Sa)();if(!a){a=(0,_.L)();(0,_.Ta)(a);var c=(0,_.L)();a.e=function(a){var g=c[a];g&&(delete c[a],g())};a.a=function(a,g){c[a]=g};a.r=function(a){delete c[a]}}return a};
_.md=function(a,c,f,g,h){var l,n;var q=f.onload;(0,_.va)(q)?((0,_.ld)().a(g,q),n=q):n=_.s;n?((0,_.Fa)(/^\w+$/.test(g),"Unsupported id - "+g),(0,_.ld)(),q='onload="window.___jsl.onl.e(&#34;'+g+'&#34;)"'):q="";try{l=a.createElement('<iframe frameborder="'+(0,_.wa)(f.frameborder)+'" scrolling="'+(0,_.wa)(f.scrolling)+'" '+q+' name="'+(0,_.wa)(f.name)+'"/>')}catch(t){l=a.createElement("iframe"),n&&(l.onload=function(){l.onload=_.s;n.call(this)},(0,_.ld)().r(g))}for(var w in f)a=f[w],"style"===w&&"object"===
typeof a?(0,_.Ea)(a,l.style):_.nd[w]||l.setAttribute(w,(0,window.String)(a));(!h||!h.dontclear)&&(0,_.Na)(c);c.appendChild(l);l=c.lastChild;f.allowtransparency&&(l.allowTransparency=_.r);return l};
_.od=function(a,c,f){var g=f||{};f=g.attributes||{};(0,_.Fa)(!g.allowPost||!f.onload,"onload is not supported by post iframe");f=c.ownerDocument||_.db;var h,l=0;do h=g.id||["I",_.pd++,"_",(new window.Date).getTime()].join("");while(f.getElementById(h)&&5>++l);(0,_.Fa)(5>l,"Error creating iframe id");var n,q=f.location.href,l=(0,_.L)(),t=(0,_.Qa)(q);t&&(l._bsh=t);(q=(0,_.Oa)(q))&&(l.jsh=q);q=(0,_.L)();q.id=h;q.parent=f.location.protocol+"//"+f.location.host;var t=(0,_.Ga)(f.location.href,"id",""),
w=(0,_.Ga)(f.location.href,"pfname","");(t=t?w+"/"+t:"")&&(q.pfname=t);g.hintInFragment?(0,_.Ea)(l,q):n=l;n=(0,_.Ma)(a,n,q);a=(0,_.L)();(0,_.Ea)(_.qd,a);(0,_.Ea)(g.attributes,a);a.name=a.id=h;a.src=n;if((g||{}).allowPost&&2E3<n.length){n=(0,_.Ha)(n);a.src="";a["data-postorigin"]=n.uc;a=(0,_.md)(f,c,a,h);var x;-1!=window.navigator.userAgent.indexOf("WebKit")&&(x=a.contentWindow.document,x.open(),l=x.createElement("div"),q={},t=h+"_inner",q.name=t,q.src="",q.style="display:none",(0,_.md)(f,l,q,t,g));
g=(0,_.Ja)(n.jb[0]);n.jb=[];l=(0,_.Ka)(n);n=f.createElement("form");n.action=l;n.method="POST";n.target=h;n.style.display="none";for(h=0;h<g.length;h++)l=f.createElement("input"),l.type="hidden",l.name=g[h][0],l.value=g[h][1],n.appendChild(l);c.appendChild(n);n.submit();n.parentNode.removeChild(n);x&&x.close();c=a}else c=(0,_.md)(f,c,a,h,g);return c};
_.qd={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};_.nd={allowtransparency:_.r,onload:_.r};_.pd=0;
_.rd=function(a){_.S.Gg[a]||(_.S.Gg[a]={},_.R.N(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,l=_.S.Gg[a][g],n;l&&window.Object.hasOwnProperty.call(l,c)?n=l[c]:window.Object.hasOwnProperty.call(_.S.Xd,a)&&(n=_.S.Xd[a]);if(n)return g=window.Array.prototype.slice.call(arguments,1),n._iframe_wrapped_rpc_&&h&&g.push(h),n.apply({},g)}(0,_.ua)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,'".'].join(""));
return _.s}));return _.S.Gg[a]};_.sd=function(a,c,f){function g(g){var l=window.Array.prototype.slice.call(arguments,0),n=l[l.length-1];if("function"===typeof n){var q=n;l.pop()}l.unshift(c,a,q,f);_.R.call.apply(_.R,l)}g._iframe_wrapped_rpc_=_.r;return g};_.td=function(a,c){var f=(0,_.I)(_.Pa,"watt",(0,_.L)());(0,_.I)(f,a,c)};_.ud=function(a){var c=(0,_.Ga)(a.location.href,"urlindex");if(c=(0,_.I)(_.Pa,"fUrl",[])[c]){var f=a.location.hash,c=c+(/#/.test(c)?f.replace(/^#/,"&"):f);a.location.replace(c)}};
_.vd=function(){_.S.Xk++;return["I",_.S.Xk,"_",(new window.Date).getTime()].join("")};_.wd=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname,f=c.lastIndexOf("/");return c.substring(0,f+1)+a};
_.xd=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.P.stringify(a):a};
_.yd=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.s,g.uc=a):(g.hash=a.substring(h+1),g.uc=a.substring(0,h));a=g.uc.indexOf("?");-1==a?g.jb=_.s:(g.jb=g.uc.substring(a+1),g.uc=g.uc.substring(0,a));a=f?g.hash?[g.hash]:[]:g.jb?[g.jb]:[];for(var l in c)c.hasOwnProperty(l)&&(h=(0,_.xd)(c[l]),a.push([(0,_.zd)(l),(0,_.zd)(h)].join("=")));f?g.hash=a.join("&"):g.jb=a.join("&");return g.uc+(g.jb?"?"+g.jb:"")+(g.hash?"#"+g.hash:"")};
_.Ad=function(){var a=(0,_.id)(_.p);return a!==_.p&&a!==_.s&&""!==a?"u/"+a+"/":""};_.Bd=function(a){a&&a.match(_.Cd)&&(0,_.$a)("googleapis.config/gcv",a)};_.Dd=function(a){_.Tc.eh.Ur(a)};_.Ed=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);return f};
_.Fd=function(a,c,f,g,h){var l=[],n;for(n in a)if(a.hasOwnProperty(n)){var q=c,t=f,w=a[n],x=g,A=(0,_.rd)(n);A[q]=A[q]||{};x=_.Q.sg(x,w);w._iframe_wrapped_rpc_&&(x._iframe_wrapped_rpc_=_.r);A[q][t]=x;l.push(n)}if(h)for(n in _.S.Xd)_.S.Xd.hasOwnProperty(n)&&l.push(n);return l.join(",")};_.Gd=function(a,c,f){var g={};if(a&&a._methods){a=a._methods.split(",");for(var h=0;h<a.length;h++){var l=a[h];g[l]=(0,_.sd)(l,c,f)}}return g};
_.Hd=function(a){return a&&a.disableMultiLevelParentRelay?_.u:_.Wc&&_.Wc._open&&"inline"!=a.style&&a.inline!==_.r&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};_.Id=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};
_.Jd=function(a,c,f,g,h,l,n,q){if(":"==a.charAt(0)){a="iframes/"+a.substring(1);var t=a+"/params",w={},x=(0,_.N)(t);(0,_.$a)(t,x||w);if(w=(0,_.N)(a+"/url"))t=a+"/url",w=w||"",w=w.replace(/:session_prefix:/g,(0,_.Ad)()),w=w.replace(/:session_index:/g,(0,_.id)(_.p)||"0"),w=w.replace(/:socialhost:/g,(0,_.N)("iframes/:socialhost:")),(0,_.$a)(t,(0,_.wd)(w));a=(0,_.N)(a)}else a={url:(0,_.wd)(a)};this.Da=a;this.openParams=this.va=c;this.Wa=f||{};this.Va=g;this.j=_.u;c=c.style;if(!this.j)if(c=c&&!_.S.pf[c]&&
_.S.nh[c]){this.k=[];var A=this;c(function(){A.j=_.r;for(var a=0,c=A.k.length;a<c;++a)A.k[a].call(A)})}else this.j=_.r;this.d={};(0,_.Kd)(this,function(){var a;(a=this.va.style)&&_.S.pf[a]?a=_.S.pf[a]:a?((0,_.sb)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=_.s):a=_.Ld;if(a){var c;if("function"===typeof a)c=a(this);else{var f={};for(c in a){var g=a[c];f[c]="function"===typeof g?_.Q.sg(a,g,this):g}c=f}for(var n in h)a=c[n],"function"===typeof a&&(0,_.Md)(this,
h[n],_.Q.sg(c,a))}l&&(0,_.Md)(this,"close",l)});this.wa=this.ac=n;this.Ji=(q||[]).slice();n&&this.Ji.unshift(n.Z())};_.Kd=function(a,c){a.j?c.call(a):a.k.push(c)};_.Md=function(a,c,f){a.d[c]=a.d[c]||[];a.d[c].push(f)};_.Nd=function(a,c){return"number"==typeof c?{value:c,ld:c+"px"}:"100%"==c?{value:100,ld:"100%",gl:_.r}:_.s};_.Od=function(a){return(0,_.yd)(a.Da.url,a.Wa,_.u)};
_.Pd=function(a,c,f,g,h,l,n){_.Jd.call(this,a,c,f,g,_.Qd,h,l,n);this.id=c.id||(0,_.vd)();this.i=c.rpcToken||window.Math.round(1E9*(0,_.Zc)());a=this.Wa;c={};f=this.Da.params||{};for(var q in a)"#"==q.charAt(0)&&(c[q.substring(1)]=a[q]),0==q.indexOf("fr-")&&(c[q.substring(3)]=a[q]),"#"==f[q]&&(c[q]=a[q]);for(var t in c)delete a["fr-"+t],delete a["#"+t],delete a[t];this.Y=c;this.o={};(0,_.Kd)(this,function(){this.Nb("open");(0,_.Ed)(this.o,this)})};
_.Rd=function(a,c,f,g,h,l,n){_.Jd.call(this,a,c,f,g,_.Sd,h,l,n);this.url=a;this.b=_.s;this.z=(0,_.vd)();(0,_.Kd)(this,function(){this.Nb("beforeparentopen");var a=(0,_.Ed)(this.Va);a._onopen=this.da;a._ready=this.Ag;a._onclose=this.H;this.Wa._methods=(0,_.Fd)(a,"..",this.z,this,_.r);var a={},c;for(c in this.Wa)a[c]=(0,_.xd)(this.Wa[c]);var f=this.Da.url;if(this.va.hideUrlFromParent){c=window.name;var g=f,f=(0,_.Od)(this),h=a,a={};a._methods=h._methods;a["#opener"]=h["#opener"];a["#urlindex"]=h["#urlindex"];
a["#opener"]&&h["#urlindex"]!=_.p?(a["#opener"]=c+","+a["#opener"],c={url:g,Wa:a}):(g=(0,_.I)(_.Pa,"fUrl",[]),h=g.length,g[h]=f,_.Pa.rUrl=_.ud,a["#opener"]=c,a["#urlindex"]=h,c=_.Tc.ja(_.cb.location.href),f=(0,_.N)("iframes/relay_url_"+(0,window.encodeURIComponent)(c))||"/_/gapi/sibling/1/frame.html",c={url:c+f,Wa:a});f=c.url;a=c.Wa}_.Wc._open({url:f,openParams:this.va,params:a,proxyId:this.z,openedByProxyChain:this.Ji})})};
_.Td=function(a,c,f,g,h,l,n){_.Jd.call(this,a,c,f,g,_.Sd,l,n);this.id=c.id||(0,_.vd)();this.i=h;g._close=this.close;this.onClosed=this.b;this.C=0;(0,_.Kd)(this,function(){this.Nb("beforeparentopen");var a=(0,_.Ed)(this.Va);this.Wa._methods=(0,_.Fd)(a,"..",this.z,this,_.r);var a=(0,_.yd)(this.Da.url,this.Wa,_.u),a=_.Ud.Qu(_.db,a,this.id,{}),c=h.El(a);this.canAutoClose=function(a){a(h.Oj(c))};h.cm(c,this);this.C=c})};_.Vd=function(a){return _.S.pf[a]};_.Wd=function(a,c){_.S.pf[a]=c}; _.Xd=function(a){a=a||{};"auto"===a.height&&(a.height=_.xb.Gh());var c=window&&_.Yd&&_.Yd.ma();c?c.Rl(a.width||0,a.height||0):_.Wc&&_.Wc._resizeMe&&_.Wc._resizeMe(a)};_.Zd=function(a){(0,_.Bd)(a)};_.Ud={};
_.S.K=_.S.K||{};_.S.K.zo=function(a){try{return!!a.document}catch(c){}return _.u};_.S.K.lk=function(a){var c=a.parent;return a!=c&&_.S.K.zo(c)?_.S.K.lk(c):a};_.S.K.Tu=function(a){var c=a.userAgent||"";a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.Yd=window.ToolbarApi,_.Yd.ma=window.ToolbarApi.getInstance,_.Yd.prototype=window.ToolbarApi.prototype,_.B=_.Yd.prototype,_.B.El=_.Yd.prototype.openWindow,_.B.Qj=_.Yd.prototype.closeWindow,_.B.cm=_.Yd.prototype.setOnCloseHandler,_.B.Oj=_.Yd.prototype.canClosePopup,_.B.Rl=_.Yd.prototype.resizeWindow;else{_.$d=_.s;_.Yd=(0,_.v)();_.Yd.ma=function(){!_.$d&&(window.external&&window.external.GTB_IsToolbar)&&(_.$d=new _.Yd);return _.$d};_.B=_.Yd.prototype;_.B.El=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.B.Qj=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.B.cm=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.B.Oj=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.B.Rl=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.Yd;window.ToolbarApi.getInstance=_.Yd.ma};
_.Cd=/^[-_.0-9A-Za-z]+$/;_.Qd={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.Sd={onBeforeParentOpen:"beforeparentopen"};_.Ld={onOpen:function(a){var c=a.va;a.Ma(c.container||c.element);return a},onClose:function(a){a.remove()}};_.zd=window.encodeURIComponent||window.escape;_.S.kp=function(a){var c=(0,_.L)();(0,_.Ea)(_.qd,c);(0,_.Ea)(a,c);return c};_.B=_.Jd.prototype;_.B.Ih=(0,_.y)("va");
_.B.Ib=(0,_.y)("Wa");_.B.Hh=(0,_.y)("Va");_.B.Jh=(0,_.y)("wa");_.B.ha=function(a,c){(0,_.Kd)(this,function(){(0,_.Md)(this,a,c)})};_.B.Ic=function(a,c){(0,_.Kd)(this,function(){var f=this.d[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};
_.B.Nb=function(a,c){var f,g=this.d[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),l=0,n=g.length;l<n;++l)try{f=g[l].apply({},h)}catch(q){(0,_.ua)(['Exception when calling callback "',a,'" with exception "',q.name,": ",q.message,'".'].join(""))}return f};(0,_.Id)(_.Pd,_.Jd);_.B=_.Pd.prototype;
_.B.Ma=function(a,c){if(!this.Da.url)return(0,_.ua)("Cannot open iframe, empty URL."),this;var f=this.id;_.S.Qc[f]=this;var g=(0,_.Ed)(this.Va);g._ready=this.Ag;g._close=this.close;g._open=this.Fl;g._resizeMe=this.Sl;g._renderstart=this.Bl;var h=this.Y;this.i&&(h.rpctoken=this.i);h._methods=(0,_.Fd)(g,f,"",this,_.r);g=(0,_.Od)(this);(0,_.yd)(g,h,_.r);this.T=a="string"===typeof a?window.document.getElementById(a):a;g=(0,_.Od)(this);g=(0,_.yd)(g,h,_.r);h={id:f};if(c){h.attributes=c;var l=c.style;if("string"===
typeof l){var n;if(l){n=[];for(var l=l.split(";"),q=0,t=l.length;q<t;++q){var w=l[q];0==w.length&&q+1==t||(w=w.split(":"),2==w.length&&w[0].match(/^[ a-zA-Z_-]+$/)&&w[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?n.push(w.join(":")):(0,_.ua)(['Iframe style "',l[q],'" not allowed.'].join("")))}n=n.join(";")}else n="";c.style=n}}this.va.allowPost&&(h.allowPost=_.r);this.b=(0,_.od)(g,a,h);_.S.Qc[f]=this;f=g;_.R.Kg(this.id,this.i);_.R.Lg(this.id,f);return this};_.B.Ia=function(a,c){this.o[a]=c};_.B.Z=(0,_.y)("id");
_.B.aa=(0,_.y)("b");_.B.Cp=(0,_.y)("T");_.B.Kc=(0,_.ba)("T");_.B.Ag=function(a){var c=(0,_.Gd)(a,this.id,"");this.wa&&"function"==typeof this.Va._ready&&(a._methods=(0,_.Fd)(c,this.wa.Z(),this.id,this,_.u),this.Va._ready(a));(0,_.Ed)(a,this);(0,_.Ed)(c,this);this.Nb("ready",a)};_.B.Bl=function(a){this.Nb("renderstart",a)};_.B.close=function(a){a=this.Nb("close",a);delete _.S.Qc[this.id];return a};_.B.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.B.Fl=function(a){var c=(0,_.Gd)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.T);if((0,_.Hd)(a.openParams))new _.Rd(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else{var f=new _.Pd(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;(0,_.Kd)(f,function(){var a={childId:f.Z()},l=f.o;l._toclose=f.close;a._methods=(0,_.Fd)(l,g.id,f.id,f,_.u);c._onopen(a)})}};
_.B.Sl=function(a){if(this.Nb("resize",a)===_.p&&this.b){var c=(0,_.Nd)(this,a.width);c!=_.s&&(this.b.style.width=c.ld);a=(0,_.Nd)(this,a.height);a!=_.s&&(this.b.style.height=a.ld);if(this.b.parentElement&&(c!=_.s&&c.gl||a!=_.s&&a.gl))this.b.parentElement.style.display="block"}};(0,_.Id)(_.Rd,_.Jd);_.Rd.prototype.i=(0,_.y)("b");
_.Rd.prototype.da=function(a){this.b=a.childId;var c=(0,_.Gd)(a,"..",this.b);(0,_.Ed)(c,this);this.close=c._toclose;_.S.Qc[this.b]=this;this.wa&&this.Va._onopen&&(a._methods=(0,_.Fd)(c,this.wa.Z(),this.b,this,_.u),this.Va._onopen(a))};_.Rd.prototype.Ag=function(a){var c=(0,window.String)(this.b),f=(0,_.Gd)(a,"..",c);(0,_.Ed)(a,this);(0,_.Ed)(f,this);this.Nb("ready",a);this.wa&&this.Va._ready&&(a._methods=(0,_.Fd)(f,this.wa.Z(),c,this,_.u),this.Va._ready(a))};
_.Rd.prototype.H=function(a){if(this.wa&&this.Va._onclose)this.Va._onclose(a);else return a=this.Nb("close",a),delete _.S.Qc[this.b],a};(0,_.Id)(_.Td,_.Jd);_.Td.prototype.close=function(a){a=this.Nb("close",a);this.i.Qj(this.C);return a};_.Td.prototype.b=function(){this.Nb("close")};_.S.Qc={};_.S.pf={};_.S.nh={};_.S.Xk=0;_.S.Gg={};_.S.Xd={};_.S.Dg=_.s;_.S.Cg=[];
_.S.dr=function(a){var c=_.u;try{if(a!=_.s)var f=window.parent.frames[a.id],c=f.iframer.id==a.id&&f.iframes.openedId_(_.Wc.id)}catch(g){}try{_.S.Dg={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.S.Cg.length;++a)_.S.Cg[a](_.S.Dg);_.S.Cg=[]}catch(h){}};_.S.up=function(a){var c=a&&a.wa,f=_.s;c&&(f={},f.id=c.Z(),f.proxyChain=a.Ji);return f};_.R.N("_noop_echo",function(){this.callback(_.S.up(_.S.Qc[this.f]))});
if(window.parent!=window){_.ae=_.Q.na();_.ae.gcv&&(0,_.Bd)(_.ae.gcv);_.be=_.ae.jsh;_.be&&(0,_.Dd)(_.be);(0,_.Ed)((0,_.Gd)(_.ae,"..",""),_.Wc);(0,_.Ed)(_.ae,_.Wc);window.setTimeout(function(){_.R.call("..","_noop_echo",_.S.dr)},0)}_.S.qa=_.Vd;_.S.la=_.Wd;_.S.Sr=_.Zd;_.S.Wc=_.Xd;_.S.ep=function(a){return _.S.nh[a]};_.S.Vi=function(a,c){_.S.nh[a]=c};_.S.xr=_.Xd;_.S.Zr=_.Zd;_.S.fg={};_.S.fg.get=_.Vd;_.S.fg.set=_.Wd;_.S.oo=function(a,c){(0,_.rd)(a);_.S.Xd[a]=c||window[a]};_.S.Nu=function(a){delete _.S.Xd[a]};
_.S.open=function(a,c,f,g,h,l){3==arguments.length?g={}:4==arguments.length&&"function"===typeof g&&(h=g,g={});var n="bubble"===c.style&&_.Yd&&_.Yd.ma();return n?new _.Td(a,c,f,g,n,h,l):(0,_.Hd)(c)?new _.Rd(a,c,f,g,h,l):new _.Pd(a,c,f,g,h,l)};_.S.close=function(a,c){_.Wc&&_.Wc._close&&_.Wc._close(a,c)};
_.S.Rb=function(a,c,f){2==arguments.length&&"function"===typeof h&&(f=c,c={});var g=a||{};"height"in g||(g.height=_.xb.Gh());var h=c||{};g._methods=(0,_.Fd)(h,"..","",_.Wc,_.r);_.Wc&&_.Wc._ready&&_.Wc._ready(g,f)};_.S.gk=function(a){_.S.Dg?a(_.S.Dg):_.S.Cg.push(a)};_.S.$q=function(a){return!!_.S.Qc[a]};_.S.ip=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.N)("googleapis.config/gcv")].join("")};
_.S.jr=function(a){var c={mouseover:1,mouseout:1};if(_.Wc._event)for(var f=0;f<a.length;f++){var g=a[f];g in c&&_.Q.xe(window.document,g,function(a){_.Wc._event({event:a.type,timestamp:(new window.Date).getTime()})},_.r)}};_.S.Vr=_.Dd;_.S.Ui=function(a){_.Tc.eh.Ui(a)};_.S.av=(0,_.v)();_.S.xq=_.Wc;
(0,_.O)("iframes.allow",_.S.oo);(0,_.O)("iframes.callSiblingOpener",_.S.yo);(0,_.O)("iframes.registerForOpenedSibling",_.S.kr);(0,_.O)("iframes.close",_.S.close);(0,_.O)("iframes.getGoogleConnectJsUri",_.S.ip);(0,_.O)("iframes.getHandler",_.S.qa);(0,_.O)("iframes.getDeferredHandler",_.S.ep);(0,_.O)("iframes.getParentInfo",_.S.gk);(0,_.O)("iframes.iframer",_.S.xq);(0,_.O)("iframes.open",_.S.open);(0,_.O)("iframes.openedId_",_.S.$q);(0,_.O)("iframes.propagate",_.S.jr);(0,_.O)("iframes.ready",_.S.Rb);
(0,_.O)("iframes.resize",_.S.Wc);(0,_.O)("iframes.setGoogleConnectJsVersion",_.S.Sr);(0,_.O)("iframes.setBootstrapHint",_.S.Ui);(0,_.O)("iframes.setJsHint",_.S.Vr);(0,_.O)("iframes.setHandler",_.S.la);(0,_.O)("iframes.setDeferredHandler",_.S.Vi);(0,_.O)("IframeBase",_.Jd);(0,_.O)("IframeBase.prototype.addCallback",_.Jd.prototype.ha);(0,_.O)("IframeBase.prototype.getMethods",_.Jd.prototype.Hh);(0,_.O)("IframeBase.prototype.getOpenerIframe",_.Jd.prototype.Jh);
(0,_.O)("IframeBase.prototype.getOpenParams",_.Jd.prototype.Ih);(0,_.O)("IframeBase.prototype.getParams",_.Jd.prototype.Ib);(0,_.O)("IframeBase.prototype.removeCallback",_.Jd.prototype.Ic);(0,_.O)("Iframe",_.Pd);(0,_.O)("Iframe.prototype.close",_.Pd.prototype.close);(0,_.O)("Iframe.prototype.exposeMethod",_.Pd.prototype.Ia);(0,_.O)("Iframe.prototype.getId",_.Pd.prototype.Z);(0,_.O)("Iframe.prototype.getIframeEl",_.Pd.prototype.aa);(0,_.O)("Iframe.prototype.getSiteEl",_.Pd.prototype.Cp);
(0,_.O)("Iframe.prototype.openInto",_.Pd.prototype.Ma);(0,_.O)("Iframe.prototype.remove",_.Pd.prototype.remove);(0,_.O)("Iframe.prototype.setSiteEl",_.Pd.prototype.Kc);(0,_.O)("Iframe.prototype.addCallback",_.Pd.prototype.ha);(0,_.O)("Iframe.prototype.getMethods",_.Pd.prototype.Hh);(0,_.O)("Iframe.prototype.getOpenerIframe",_.Pd.prototype.Jh);(0,_.O)("Iframe.prototype.getOpenParams",_.Pd.prototype.Ih);(0,_.O)("Iframe.prototype.getParams",_.Pd.prototype.Ib);
(0,_.O)("Iframe.prototype.removeCallback",_.Pd.prototype.Ic);(0,_.O)("IframeProxy",_.Rd);(0,_.O)("IframeProxy.prototype.getTargetIframeId",_.Rd.prototype.i);(0,_.O)("IframeProxy.prototype.addCallback",_.Rd.prototype.ha);(0,_.O)("IframeProxy.prototype.getMethods",_.Rd.prototype.Hh);(0,_.O)("IframeProxy.prototype.getOpenerIframe",_.Rd.prototype.Jh);(0,_.O)("IframeProxy.prototype.getOpenParams",_.Rd.prototype.Ih);(0,_.O)("IframeProxy.prototype.getParams",_.Rd.prototype.Ib);
(0,_.O)("IframeProxy.prototype.removeCallback",_.Rd.prototype.Ic);(0,_.O)("IframeWindow",_.Td);(0,_.O)("IframeWindow.prototype.close",_.Td.prototype.close);(0,_.O)("IframeWindow.prototype.onClosed",_.Td.prototype.b);(0,_.O)("iframes.util.getTopMostAccessibleWindow",_.S.K.lk);(0,_.O)("iframes.handlers.get",_.S.fg.get);(0,_.O)("iframes.handlers.set",_.S.fg.set);(0,_.O)("iframes.resizeMe",_.S.xr);(0,_.O)("iframes.setVersionOverride",_.S.Zr);

_.ce=(0,_.I)(_.Pa,"rw",(0,_.L)());
_.de=function(a,c){var f=_.ce[a];f&&f.state<c&&(f.state=c)};_.ee=function(a){a=(a=_.ce[a])?a.oid:_.p;if(a){var c=_.db.getElementById(a);c&&c.parentNode.removeChild(c);delete _.ce[a];(0,_.ee)(a)}};_.fe=function(a){a=a.style;a.textIndent="0";a.margin="0";a.padding="0";a.background="transparent";a.borderStyle="none";a.cssFloat="none";a.styleFloat="none";a.lineHeight="normal";a.fontSize="1px";a.verticalAlign="baseline"};
_.ge=function(a){a=a.va.container;"string"===typeof a&&(a=window.document.getElementById(a));return a};_.he=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.ie=function(a,c){var f={};f.width=c?c.width:a.width;f.height=c?c.height:a.height;var g=a.aa(),h=a.Z();(0,_.de)(h,2);(h=_.ce[h])&&(h.args=f);a:{var h=g.parentNode,f=f||{},l=_.Pa.ssfn;if(l&&l()){if("number"===typeof _.Pa.ucs)break a;var n=g.id;if(n){l=(l=_.ce[n])?l.state:_.p;if(1===l||4===l)break a;(0,_.ee)(n)}}l=f.width;f=f.height;(0,_.fe)(h);h.style.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";l&&(g.width=l+"px");f&&(g.height=f+"px");n&&(0,_.de)(n, 3)}(n=c?c.title:_.s)&&a.aa().setAttribute("title",n)};
_.je={open:function(a){var c=(0,_.ge)(a);return a.Ma(c,{style:(0,_.he)(c,a)})},attach:function(a,c){var f=(0,_.ge)(a),g=c.id,h=c.getAttribute("data-postorigin")||c.src,l=/#(?:.*&)?rpctoken=(\d+)/.exec(h),l=l&&l[1];a.id=g;a.i=l;a.T=c.parentNode;a.b=c;_.S.Qc[g]=a;l=(0,_.Ed)(a.Va);l._ready=a.Ag;l._close=a.close;l._open=a.Fl;l._resizeMe=a.Sl;l._renderstart=a.Bl;(0,_.Fd)(l,g,"",a,_.r);_.R.Kg(a.id,a.i);_.R.Lg(a.id,h);var f=_.S.kp({style:(0,_.he)(f,a)}),n;for(n in f)window.Object.prototype.hasOwnProperty.call(f, n)&&("style"==n?a.b.style.cssText=f[n]:a.b.setAttribute(n,f[n]))}};_.je.onready=_.ie;_.je.onRenderStart=_.ie;_.je.close=function(a){var c=a.T;c&&c.removeChild(a.aa())};_.S.la("inline",_.je);


_.ke=function(a){var c;a.match(/^https?%3A/i)&&(c=(0,window.decodeURIComponent)(a));a=c?c:a;c=window.document.createElement("div");var f=window.document.createElement("a");f.href=a;c.appendChild(f);c.innerHTML=c.innerHTML;a=(0,window.String)(c.firstChild.href);c.parentNode&&c.parentNode.removeChild(c);return a};_.me=function(a){a=a||"canonical";for(var c=window.document.getElementsByTagName("link"),f=0,g=c.length;f<g;f++){var h=c[f],l=h.getAttribute("rel");if(l&&l.toLowerCase()==a&&(h=h.getAttribute("href")))return(0,_.ke)(h)}return window.location.href};
_.ne=function(a,c,f,g){return(a="string"==typeof a?a:_.p)?(0,_.ke)(a):(0,_.me)(g)};_.oe=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.pe=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.qe=function(a){if((0,_.oe)(a))return"true"};_.re=function(a){return"string"==typeof a&&_.se[a.toLowerCase()]?a.toLowerCase():"standard"};_.te=function(a,c){return"tall"==(0,_.re)(c)?"true":a==_.s||(0,_.oe)(a)?"true":"false"};
_.ue=function(a,c,f){a==_.s&&f&&(a=f.db,a==_.s&&(a=f.gwidget&&f.gwidget.db));return a||_.p};_.ve=function(a,c,f){a==_.s&&f&&(a=f.ecp,a==_.s&&(a=f.gwidget&&f.gwidget.ecp));return a||_.p};_.se={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.we={href:[_.ne,"url"],width:[_.pe],size:[_.re],resize:[_.qe],autosize:[_.qe],count:[function(a,c){return(0,_.te)(c.count,c.size)}],db:[_.ue],ecp:[_.ve],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.qe],recommendations:[],fu:[],ad:[_.qe],cr:[_.pe],ag:[_.pe],"fr-ai":[],"fr-sigh":[]};


_.xe=(0,_.Ra)();
_.ye=function(a,c){if(!_.ze){var f=(0,_.N)("iframes/:socialhost:"),g=(0,_.id)(_.p)||"0",h=(0,_.id)(_.p);_.ze={socialhost:f,session_index:g,session_prefix:h!==_.p&&h!==_.s&&""!==h?"u/"+h+"/":"",im_prefix:(0,_.N)("googleapis.config/signedIn")===_.u?"_/im/":""}}return _.ze[c]||""};_.Ae=function(a,c,f){return(0,_.ne)(a,c,f,c.action?_.p:"publisher")};_.Be=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
_.Ce=function(a){var c=_.p;"number"===typeof a?c=a:"string"===typeof a&&(c=(0,window.parseInt)(a,10));return c};_.De=function(a,c){if("string"==typeof a){a=a.toLowerCase();var f;for(f=0;f<c.length;f++)if(c[f]==a)return a}};_.Ee=function(a){return(0,_.De)(a,_.Fe)};_.Ge=function(a){return(0,_.De)(a,_.He)};_.Ie=function(a){a.source=[_.s,"source"];a.expandTo=[_.s,"expandTo"];a.align=[_.Ge];a.annotation=[_.Ee];a.origin=[_.Be]};
_.Je=function(a){if(_.Ca.test(window.Object.keys))return window.Object.keys(a);var c=[],f;for(f in a)(0,_.Da)(a,f)&&c.push(f);return c};
_.Ke=function(a,c){_.Le.ps0=(new window.Date).getTime();(0,_.Me)("ps0");var f=("string"===typeof a?window.document.getElementById(a):a)||_.db,g;g=_.db.documentMode;if(f.querySelectorAll&&(!g||8<g)){g=c?[c]:(0,_.Je)(_.Ne).concat((0,_.Je)(_.Oe)).concat((0,_.Je)(_.Pe));for(var h=[],l=0;l<g.length;l++){var n=g[l];h.push(".g-"+n,"g\\:"+n)}g=f.querySelectorAll(h.join(","))}else g=f.getElementsByTagName("*");f=(0,_.L)();for(h=0;h<g.length;h++){l=g[h];var q=l,n=c,t=q.nodeName.toLowerCase(),w=_.p;q.getAttribute("data-gapiscan")?
n=_.s:(0==t.indexOf("g:")?w=t.substr(2):(q=(q=(0,window.String)(q.className||q.getAttribute("class")))&&_.Qe.exec(q))&&(w=q[1]),n=w&&(_.Ne[w]||_.Oe[w]||_.Pe[w])&&(!n||w===n)?w:_.s);n&&(l.setAttribute("data-gapiscan",_.r),(0,_.I)(f,n,[]).push(l))}for(var x in f)_.Re.push(x);_.Le.ps1=(new window.Date).getTime();(0,_.Me)("ps1");(x=_.Re.join(":"))&&_.eb.load(x,_.p);var A,l=[];for(A in f){h=f[A];g=0;for(x=h.length;g<x;g++){for(var q=h[g],n=A,t=w=q,q=(0,_.L)(),E=0!=t.nodeName.toLowerCase().indexOf("g:"),
J=0,K=t.attributes.length;J<K;J++){var M=t.attributes[J],V=M.name,M=M.value;0<=_.vb.call(_.Se,V)||(E&&0!=V.indexOf("data-")||"null"===M)||(E&&(V=V.substr(5)),q[V.toLowerCase()]=M)}t=t.style;(E=(0,_.Ce)(t&&t.height))&&(q.height=(0,window.String)(E));(t=(0,_.Ce)(t&&t.width))&&(q.width=(0,window.String)(t));(0,_.Te)(n,w,q,l,x)}}};
_.Ue=function(a,c){var f=(0,_.I)(_.Pa,"watt",(0,_.L)())[a];c&&f?f(c):_.eb.load(a,function(){var f=(0,_.I)(_.Pa,"watt",(0,_.L)())[a],h=c&&c.iframeNode;!h||!f?(0,_.eb[a].go)(h&&h.parentNode):f(c)})};
_.Te=function(a,c,f,g,h){switch((0,_.Ve)(c,a)){case 0:case 1:g={};g.iframeNode=c;g.userParams=f;(0,_.Ue)(a,g);break;case 2:if(c.parentNode){var l=_.r;f.dontclear&&(l=_.u);delete f.dontclear;var n;var q;c:{var t=a,w=a;"plus"==a&&f.action&&(t=a+"_"+f.action,w=a+"/"+f.action);q=(0,_.N)("iframes/"+t+"/url");if(!q){if((0,_.I)(_.Pa,"SM",(0,_.L)())[t]){q=_.s;break c}q=":socialhost:/_/widget/render/"+w}q=q.replace(_.We,_.ye)}if(q){t={};(0,_.Ea)(f,t);t.hl=(0,_.N)("lang")||"en-US";t.origin=(0,_.Be)();t.exp=
(0,_.N)("iframes/"+a+"/params/exp");if(w=(0,_.N)("iframes/"+a+"/params/location"))for(var x=0;x<w.length;x++){var A=w[x];t[A]=_.cb.location[A]}switch(a){case "plus":t.url=(0,_.Ae)(t.href,f,_.s);delete t.href;break;case "plusone":case "recobox":t.url=f.href?(0,_.ke)(f.href):(0,_.me)();t.db=(0,_.ue)(f.db,_.p,(0,_.N)());t.ecp=(0,_.ve)(f.ecp,_.p,(0,_.N)());delete t.href;break;case "signin":t.url=(0,_.me)()}t.hl=(0,_.N)("lang")||"en-US";_.Pa.ILI&&(t.iloader="1");delete t["data-onload"];delete t.rd;w=(0,_.N)("inline/css");
"undefined"!==typeof w&&(0<h&&w>=h)&&(t.ic="1");w=/^#|^fr-/;h={};for(var E in t)(0,_.Da)(t,E)&&w.test(E)&&(h[E.replace(w,"")]=t[E],delete t[E]);E=[].concat(_.Xe);w=(0,_.N)("iframes/"+a+"/methods");"object"===typeof w&&_.Ca.test(w.push)&&(E=E.concat(w));for(n in f)if((0,_.Da)(f,n)&&/^on/.test(n)&&("plus"!=a||"onconnect"!=n))E.push(n),delete t[n];delete t.callback;h._methods=E.join(",");n=(0,_.Ma)(q,t,h)}else n=_.s;n?(f.rd?E=c:(E=window.document.createElement("div"),c.setAttribute("data-gapistub",_.r),
E.style.cssText="position:absolute;width:100px;left:-10000px;",c.parentNode.insertBefore(E,c)),E.id||(c=E,(0,_.I)(_.xe,a,0),q="___"+a+"_"+_.xe[a]++,c.id=q),c=(0,_.L)(),c[">type"]=a,(0,_.Ea)(f,c),E.setAttribute("data-gwattr",(0,_.La)(c).join(":")),c=E,E={allowPost:1,attributes:_.Ye},E.dontclear=!l,c=(0,_.od)(n,c,E),l={},l.userParams=f,l.url=n,l.type=a,l.iframeNode=c,l.id=c.getAttribute("id"),f=l.id,c=(0,_.L)(),c.id=f,c.userParams=l.userParams,c.url=l.url,c.type=l.type,c.state=1,_.ce[f]=c,f=l):f=_.s}else f=
_.s;f&&((l=f.id)&&g.push(l),(0,_.Ue)(a,f))}};_.Ve=function(a,c){if(a&&1===a.nodeType&&c){if(_.Oe[c])return 1;var f;if(f=_.Pe[c])if(f=!!_.Ze[a.nodeName.toLowerCase()])f=(f=a.innerHTML)&&f.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")?_.r:_.u;if(f)return 0;if(_.Ne[c])return 2}return _.s};_.$e=function(a,c,f,g){_.af[f]=_.af[f]||!!g;(0,_.I)(_.bf,f,[]);_.bf[f].push([a,c])};_.Me=function(a,c,f){var g=_.cf.r;"function"===typeof g?g(a,c,f):g.push([a,c,f])};
_.df=function(a,c,f,g){"_p"==c&&(0,_.m)((0,window.Error)("m`_p"));(0,_.ef)(c,f)[a]=g||(new window.Date).getTime();(0,_.Me)(a,c,f)};_.ef=function(a,c){var f=(0,_.I)(_.ff,a,(0,_.L)());return(0,_.I)(f,c,(0,_.L)())};_.gf=function(a,c,f){var g=_.s;c&&f&&(g=(0,_.ef)(c,f)[a]);return g||_.Le[a]};_.hf=function(a){this.t={};this.tick=function(a,f,g){this.t[a]=[g!=_.p?g:(new window.Date).getTime(),f]};this.tick("start",_.s,a)};_.jf=function(a,c){this.type=!a?"g":"_p"==a?"m":"w";this.name=a;this.b=c};
_.kf=function(a){var c=[];c.push("l"+((0,_.N)("isPlusUser")?"1":"0"));var f="m"+(_.lf?"1":"0");c.push(f);if("m"==a.type)c.push("p"+a.b);else if("w"==a.type){var g="n"+a.b;c.push(g);"0"==a.b&&c.push(f+g)}return c};_.mf=function(a,c,f){for(var g=new _.jf(c,f),h=(0,_.I)(_.nf,g.key(),(0,_.L)()),l=_.bf[a]||[],n=0;n<l.length;++n){var q=l[n],t=h,w=q[0],x=a,A=c,E=f,q=(0,_.gf)(q[1],A,E),x=(0,_.gf)(x,A,E);t[w]=q&&x?x-q:_.s}_.af[a]&&_.of&&((0,_.pf)(_.qf),(0,_.pf)(g))};
_.rf=function(a,c){c=c||[];for(var f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};
_.pf=function(a){var c=_.cb.__gapi_jstiming__;c.sn=_.sf[a.type];var f=new c.Timer(0),g;a:{switch(a.type){case "g":g="global";break a;case "m":g=a.b;break a;case "w":g=a.name;break a}g=_.p}f.name=g;g=_.u;var h=a.key(),l=_.nf[h];f.tick("_start",_.s,0);for(var n in l)f.tick(n,"_start",l[n]),g=_.r;_.nf[h]=(0,_.L)();if(g){n=[];g=(0,_.N)("lexps");n=n.concat((0,_.rf)("e",g));n=n.concat((0,_.rf)("",(0,_.kf)(a)));for(h=0;h<_.tf.length;h++)l=_.tf[h],0<=_.vb.call(g,l)&&(n=n.concat((0,_.rf)(l?"e"+l:"",(0,_.kf)(a))));
n=(0,_.rf)("abc_",n);c.report(f,{e:n.join(",")})}};_.uf=function(a){var c=(0,_.N)(a);return"undefined"!==typeof c?c:(0,_.N)("gwidget/"+a)};_.vf=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};_.wf=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.s};_.xf=function(a,c,f,g){return _.S.open(a,c,f,g)};
_.yf=function(a,c){for(var f in _.zf)if(_.zf.hasOwnProperty(f)){var g=_.zf[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};_.Af=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||_.Bf)(c[g],c,_.Cf));return f};_.Bf=function(a){return a};_.Df=function(){};_.ze=_.s;_.We=/:([a-zA-Z_]+):/g;_.Xe="onPlusOne _ready _close,_open _resizeMe _renderstart oncircled".split(" ");_.Fe="inline bubble none only pp vertical-bubble".split(" ");_.He=["left","right"];
_.Se=["style","data-gapiscan"];_.Ye={style:"position:absolute;top:-10000px;width:300px;margin:0px;borderStyle:none"};_.Qe=/(?:^|\s)g-((\S)*)(?:$|\s)/;_.Ze={button:_.r,div:_.r,span:_.r};_.Ne=(0,_.I)(_.Pa,"SW",(0,_.L)());_.Oe=(0,_.I)(_.Pa,"SA",(0,_.L)());_.Pe=(0,_.I)(_.Pa,"SM",(0,_.L)());_.Re=(0,_.I)(_.Pa,"FW",[]);
(0,_.I)(_.eb,"platform",{}).go=_.Ke;_.cf=(0,_.I)(_.Pa,"perf",(0,_.L)());_.Le=(0,_.I)(_.cf,"g",(0,_.L)());_.ff=(0,_.I)(_.cf,"i",(0,_.L)());(0,_.I)(_.cf,"r",[]);_.af=(0,_.L)();_.bf=(0,_.L)();_.Ef=new _.hf;window.__gapi_jstiming__={Timer:_.hf,load:_.Ef};if(window.performance&&window.performance.timing){_.Ff=window.performance.timing;_.Gf=window.__gapi_jstiming__.load;_.Hf=_.Ff.navigationStart;_.If=_.Ff.responseStart;0<_.Hf&&_.If>=_.Hf&&(_.Gf.tick("_wtsrt",_.p,_.Hf),_.Gf.tick("wtsrt_","_wtsrt",_.If),_.Gf.tick("tbsd_","wtsrt_"))}
try{_.Jf=_.s;window.chrome&&window.chrome.csi&&(_.Jf=window.Math.floor(window.chrome.csi().pageT),_.Gf&&0<_.Hf&&(_.Gf.tick("_tbnd",_.p,window.chrome.csi().startE),_.Gf.tick("tbnd_","_tbnd",_.Hf)));_.Jf==_.s&&window.gtbExternal&&(_.Jf=window.gtbExternal.pageT());_.Jf==_.s&&window.external&&(_.Jf=window.external.pageT,_.Gf&&0<_.Hf&&(_.Gf.tick("_tbnd",_.p,window.external.startE),_.Gf.tick("tbnd_","_tbnd",_.Hf)));_.Jf&&(window.__gapi_jstiming__.pt=_.Jf)}catch(Kf){};
if(window.__gapi_jstiming__){window.__gapi_jstiming__.Mj={};window.__gapi_jstiming__.rr=1;_.Lf=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.p?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.Lf;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.Mf=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var l=window.chrome;if(l&&(l=l.loadTimes)){l().wasFetchedViaSpdy&&(g+="&p=s");if(l().wasNpnNegotiated){var g=g+"&npn=1",n=l().npnNegotiatedProtocol;n&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(n))}l().wasAlternateProtocolAvailable&&(g+="&apa=1")}var q=a.t,t=q.start,l=[],n=[],w;for(w in q)if("start"!=w&&0!=w.indexOf("_")){var x=q[w][1];x?q[x]&&
n.push(w+"."+(0,_.Lf)(a,w,q[x][0])):t&&l.push(w+"."+(0,_.Lf)(a,w))}if(c)for(var A in c)g+="&"+A+"="+c[A];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");a=[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,n.length?"&it="+n.join(","):"","",g,"&rt=",l.join(",")].join("");if(!a)return"";var g=new window.Image,E=window.__gapi_jstiming__.rr++;window.__gapi_jstiming__.Mj[E]=g;g.onload=g.onerror=function(){window.__gapi_jstiming__&&
delete window.__gapi_jstiming__.Mj[E]};g.src=a;g=_.s;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.u,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var l;"prerender"==window.document.webkitVisibilityState?l=_.u:((0,_.Mf)(a,c,f),l=_.r);l&&(g=_.r,window.document.removeEventListener("webkitvisibilitychange",h,_.u))}};window.document.addEventListener("webkitvisibilitychange",h,_.u);return""}return(0,_.Mf)(a,c,f)}};
_.tf=[73,74,77,78];_.sf={g:"gapi_global",m:"gapi_module",w:"gwidget"};_.jf.prototype.key=function(){switch(this.type){case "g":return this.type;case "m":return this.type+"."+this.b;case "w":return this.type+"."+this.name+this.b}};_.qf=new _.jf;_.lf=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/);_.nf=(0,_.I)(_.cf,"_c",(0,_.L)());_.of=window.Math.random()<((0,_.N)("csi/rate")||0);(0,_.$e)("blt","bs0","bs1");(0,_.$e)("psi","ps0","ps1");(0,_.$e)("rpcqi","rqe","rqd");
(0,_.$e)("mli","ml0","ml1");(0,_.$e)("mei","me0","me1",_.r);(0,_.$e)("wci","wrs","wdc");(0,_.$e)("wdi","wrs","wrdi");(0,_.$e)("wdt","bs0","wrdt");(0,_.$e)("wri","wrs","wrri",_.r);(0,_.$e)("wrt","bs0","wrrt");(0,_.$e)("wji","wje0","wje1",_.r);(0,_.$e)("wjli","wjl0","wjl1");(0,_.$e)("whi","wh0","wh1",_.r);_.Nf=_.cf.r;if("function"!==typeof _.Nf){for(_.Of;_.Of=_.Nf.shift();)_.mf.apply(_.s,_.Of);_.cf.r=_.mf};
_.Qf=["div"];_.Rf="onload";_.Sf=_.r;_.Cf=_.s;_.Cf=(0,_.N)();(0,_.N)("gwidget");_.Tf=(0,_.uf)("parsetags");_.Rf="explicit"===_.Tf||"onload"===_.Tf?_.Tf:_.Rf;_.Uf=(0,_.uf)("google_analytics");"undefined"!==typeof _.Uf&&(_.Sf=!!_.Uf);_.Vf={};_.Vf.width=[(0,_.vf)(450)];_.Vf.height=[(0,_.vf)(24)];_.Vf.callback=[_.wf];_.Vf.onready=[_.wf];_.Vf.lang=[function(){return(0,_.uf)("lang")||"en-US"},"hl"];_.Vf.iloader=[function(){return _.Pa.ILI},"iloader"];_.zf=_.Vf;
_.Pf={Ka:function(a){function c(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[h.ts]=1;h.Kq=c}function f(){"onload"===_.Rf&&q.go()}var g,h={};h.Bb=a[0];h.nj=-1;h.Em="___"+h.Bb+"_";h.ts="g:"+h.Bb;h.Xu="g-"+h.Bb;h.Pl=[];h.Da={};h.gh=[];h.xh=[];a[1]&&(h.ar=a[1]);h.Da=a[2]||{};for(var l in _.zf)_.zf.hasOwnProperty(l)&&!h.Da.hasOwnProperty(l)&&(h.Da[l]=_.zf[l]);a[3]&&(h.gh=a[3]);a[4]&&c(a[4]);a[5]&&(h.ie=a[5]);h.mv=a[7]===_.r;h.hr=a[8];h.Kq||c(_.Qf);if(a=a[6])if("number"==typeof a.length){h.xh=
a;for(var n=a.length-1;0<=n;--n)h.Da[a[n]]=[_.wf]}else for(n in a)a.hasOwnProperty(n)&&!h.Da.hasOwnProperty(n)&&(h.xh.push(n),h.Da[n]=a[n]);h.Hi=function(a){function c(){Xr||(Xr=_.r,f(),Yr&&(0,_.df)("wrrt",kc,lc),(0,_.df)("wrri",kc,lc))}function f(){Zr||(Zr=_.r,Tb.aa(),Yr&&(0,_.df)("wrdt",kc,lc),(0,_.df)("wrdi",kc,lc))}function g(a){a=a||Tb;var c=(0,_.Nd)(Tb,a.width);c&&ri.style.width!=c.ld&&(ri.style.width=c.ld);if((a=(0,_.Nd)(Tb,a.height))&&ri.style.height!=a.ld)ri.style.height=a.ld}h.nj++;(0,_.df)("wrs",
h.Bb,(0,window.String)(h.nj));var l=[];h.ie&&(l[0]=a.element,l[1]=a.Hg,h.ie("s",l),a.Hg=l[1]);var n=a.element,q=n.parentNode,t=a.Da;if(0===a.Hg){var qa=window.document.createElement("div");q.insertBefore(qa,n);q.removeChild(n);n=qa}qa=n.style;if(n.id){if(0===n.id.indexOf(h.Em)){var ea=n.nextSibling;ea&&(ea.getAttribute&&ea.getAttribute("data-gapistub"))&&q.removeChild(ea);qa.cssText=""}}else{var q=n,ea=h.Em,sa=h.Bb,qb=(0,_.Ra)();window.Object.prototype.hasOwnProperty.call(qb,sa)||(qb[sa]=0);var si=
qb[sa];qb[sa]=si+1;q.id=ea+si}t.height&&(qa.height=t.height+"px");t.width&&(qa.width=t.width+"px");qa.display||(qa.display="inline-block");(0,_.fe)(n);var le=":"+h.Bb;":plus"==le&&(a.he&&a.he.action)&&(le+="_"+a.he.action);var qa={},q=h.gh[0],ea=t.callback,Ub=h.gh[1];if(Ub&&_.Sf)var LA=ea||(0,_.v)(),ea=function(a){var c=Ub(a);if(c&&window._gat)try{var f=window._gat._getTrackerByName("~0");f&&"UA-XXXXX-X"!=f._getAccount()?f._trackSocial("Google",c,a.href||_.s):window._gaq&&window._gaq.push(["_trackSocial",
"Google",c,a.href||_.s])}catch(g){}LA(a)};q&&ea&&(qa[q]=ea);q=h.xh;for(ea=q.length-1;0<=ea;--ea){var Cc=q[ea];(sa=t[Cc])&&(qa[Cc]=sa)}q={};for(Cc in a.he)a.he[Cc]!=_.s&&(q[Cc]=a.he[Cc]);Cc={container:n.id,renderData:a.qr,style:"inline",height:t.height,width:t.width};if(!_.S.qa("attach")){var ea={},ti=_.S.qa("inline"),ui;for(ui in ti)ti.hasOwnProperty(ui)&&(ea[ui]=ti[ui]);ea.open=function(a){var c=window.document.getElementById(a.va.renderData.id);c||(0,_.m)((0,window.Error)("n"));return ti.attach(a,
c)};_.S.la("attach",ea)}Cc.style="attach";h.ie&&(l[2]=Cc,l[3]=q,l[4]=qa,h.ie("i",l),a.Hg=l[1]);var Tb=function(a){var c=_.xf.apply(_.s,[le].concat([].slice.call(arguments,0)));if(t.onready){var f=_.u,g=function(){f||(f=_.r,t.onready.call(_.s))};c.ha("ready",g);c.ha("renderstart",g)}(0,_.Df)(c);return c}(Cc,q,qa),ri=n;Tb.ha("ready",g);Tb.ha("renderstart",g);Tb.ha("resize",g);var Yr=a.Lo,kc=h.Bb,lc=(0,window.String)(h.nj),Zr=_.u;Tb.ha("renderstart",f);var Xr=_.u;Tb.ha("ready",c);_.R.N("widget-interactive-"+
Tb.id,c);_.R.N("widget-csi-tick-"+Tb.id,function(a,c,f){"wdc"===a||"wci"===a?(0,_.df)("wdc",kc,lc,f):"wje0"===a||"wji_"===a?(0,_.df)("wje0",kc,lc,f):"wje1"===a||"wji"===a?(0,_.df)("wje1",kc,lc,f):"wh0"==a?((0,_.ef)(kc,lc).wh0=f||(new window.Date).getTime(),(0,_.Me)("wh0",kc,lc)):"wh1"==a&&((0,_.ef)(kc,lc).wh1=f||(new window.Date).getTime(),(0,_.Me)("wh1",kc,lc))});l[5]=Tb;h.ie&&h.ie("e",l)};g=h;if(n=g.hr)for(a=0;a<n.length;a++)(new window.Image).src=n[a];(0,_.td)(g.Bb,function(a){var c=a.userParams,
f=a.iframeNode;if((f=f&&f.parentNode)&&1===f.nodeType){f.removeAttribute("data-gwattr");var h=(0,_.Af)(g.Da,c);g.Pl.push({element:f,Da:h,he:(0,_.yf)(h,(0,_.Af)(g.ar,c)),Hg:3,Lo:!!c["data-onload"],qr:a})}a=g.Pl;for(c=g.Hi;0<a.length;)c(a.shift())});_.Ne[g.Bb]=_.r;var q={I:function(a,c){var f=c||{};f.type=g.Bb;var h=f.type;delete f.type;var l=("string"===typeof a?window.document.getElementById(a):a)||_.p,n={},q;for(q in f)(0,_.Da)(f,q)&&(n[q.toLowerCase()]=f[q]);n.rd=1;(0,_.Te)(h,l,n,[],0)},go:function(a){(0,_.Ke)(a, g.Bb)},b:function(){var a=(0,_.Ra)(),c;for(c in a)delete a[c]}},n=g.Bb;a=(0,_.I)(_.Pa,"sws",[]);if(!(0<=_.vb.call(a,n))){if("complete"!==_.db.readyState)try{f()}catch(t){}(0,_.Yc)(f)}return q}};

_.ku=(window.gapi||{}).load;
_.S.Vi("bubble",function(a){(0,_.ku)("iframes-styles-bubble",a)});
_.S.Vi("slide-menu",function(a){(0,_.ku)("iframes-styles-slide-menu",a)});

_.Ov=function(a,c,f){a=(0,_.Ee)(a);c=(0,_.re)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.se[c]["false"].height};if("bubble"!=a){if("none"==a)return _.se[c]["false"];if("pp"==a)return _.Pv}}return _.se[c]["true"]};_.Pv={width:180,height:35};_.Qv={"0":"plusone"};_.Rv=(0,_.N)("iframes/plusone/preloadUrl");_.Rv&&(_.Qv[8]=_.Rv);(0,_.Ie)(_.we);_.Qv[1]=_.we;
_.Qv[2]={width:[function(a,c){return c.annotation?(0,_.Ov)(c.annotation,c.size,c).width:_.se[(0,_.re)(c.size)][(0,_.te)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.Ov)(c.annotation,c.size,c).height:_.se[(0,_.re)(c.size)][(0,_.te)(c.count,c.size)].height}]};_.Qv[3]=["onPlusOne",function(a){return"on"==a.state?"+1":_.s}];_.Qv[4]=["div","button"];_.Qv[6]=["onstartinteraction","onendinteraction","onpopup"];_.kb=_.lb=_.Pf.Ka(_.Qv);
(0,_.O)("gapi.plusone.render",_.lb.I);(0,_.O)("gapi.plusone.go",_.lb.go);(0,_.O)("googleapisv0.plusone.render",_.kb.I);(0,_.O)("googleapisv0.plusone.go",_.kb.go);
});

// Copyright 2002-2012 Google Inc.
