/* Variables header for application - AppBuilder 2.01  */

#if defined(__cplusplus)
extern "C" {
#endif

/* 'base' Window link */
const int ABN_base = 0;
const int ABN_SearchButton = 1;
const int ABN_PtMyButton = 2;
const int ABN_PlatformButton = 3;

/* 'Search' Window link */
const int ABN_Search = 4;
const int ABN_TextString = 5;
const int ABN_SearchNow = 6;


#if defined(__cplusplus)
}
#endif

