#include <sys/neutrino.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/syspage.h>

int main( void )
{
    uint64_t cps, cycle1, cycle2, realtime;
    uint32_t CPUSpeed, flags;
    float sec, ncycles;
    struct _clockperiod CurrentPeriod, NewPeriod;
    unsigned long boottime;
    struct _clockadjust adjust;

    /* snap the time */
    cycle1 = ClockCycles( );

    /* do something */
	sleep(1);
	
    /* snap the time again */
    cycle2 = ClockCycles( );
    ncycles = cycle2 - cycle1;
    printf("%d cycles elapsed\n", ncycles);
    
    /* find out how many cycles per second */
    cps = SYSPAGE_ENTRY(qtime)->cycles_per_sec;									// cycles per second generated by hardware
    printf( "this system has %lld cycles per second\n", cps );
    sec = ncycles/cps;
    printf("the cycles in seconds is %f\n", sec);
    
    ClockPeriod(CLOCK_REALTIME, NULL, &CurrentPeriod, 0);						// get the resolution of the system clock
    printf("current clock period: %d\n", CurrentPeriod.nsec);
    
    NewPeriod.nsec = 500000;																	// set the clock tick rate to 500ms
    NewPeriod.fract = 0;
    ClockPeriod(CLOCK_REALTIME, &NewPeriod, &CurrentPeriod, 0);			// set the resolution of the system clock
    
    ClockPeriod(CLOCK_REALTIME, NULL, &CurrentPeriod, 0);						// get the new resolution of the system clock
    printf("current clock period: %d\n", CurrentPeriod.nsec);
    
    boottime = SYSPAGE_ENTRY(qtime)->boot_time;
    printf("system boot time: %lld\n", boottime);											// UTC seconds when machine booted
    
    CPUSpeed = SYSPAGE_ENTRY(cpuinfo)->speed;
    printf("CPU speed is %d MHz\n", CPUSpeed);
 
    flags = SYSPAGE_ENTRY(cacheattr)->flags;  
    if(flags & CACHE_FLAG_WRITEBACK)
    		printf("cache does writeback, not writethru\n");
    if(!(flags & CACHE_FLAG_SNOOPED))
    		printf("cache implements NO bus snooping\n");								// other processors and devs can read and manipulate
    																												// the cache in order to synchronize and update the cache
    
    	if(flags & CACHE_FLAG_SHARED)
    		printf("cache is shared between multiple processors in a SMP system\n");				// Neutrino is a SMP kernel
    	
    	ClockTime(CLOCK_REALTIME, 0, &realtime);
    	printf("system time: %lld\n", realtime);
    	
    	adjust.tick_nsec_inc = 1;
    	adjust.tick_count = 3;
    	ClockAdjust(CLOCK_REALTIME, &adjust, NULL);										// forwards the clock 1ns on each clock tick for 3 times

    return EXIT_SUCCESS;
}