
(function(){var g=null;function k(a){this.t={};this.tick=function(a,c,e){e=e?e:(new Date).getTime();this.t[a]=[e,c]};this.tick("start",g,a)}var l=new k;window.GA_jstiming={Timer:k,load:l};if(window.GA_jstiming){window.GA_jstiming.e={};window.GA_jstiming.i=1;var m=function(a,b,c){var e=a.t[b],d=a.t.start;if(e&&(d||c))return e=a.t[b][0],d=c!=void 0?c:d[0],e-d};window.GA_jstiming.report=function(a,b,c){var e="";a.h&&(e+="&"+a.h);var d=a.t,f=d.start,h=[],o=[],i;for(i in d)if(i!="start"&&i.indexOf("_")!=0){var p=d[i][1];p?d[p]&&o.push(i+"."+m(a,i,d[p][0])):f&&h.push(i+"."+m(a,i))}delete d.start;if(b)for(var t in b)e+="&"+t+"="+b[t];var a=[c?c:"http://csi.gstatic.com/csi","?v=3","&s="+(window.GA_jstiming.sn||
"gam")+"&action=",a.name,o.length?"&it="+o.join(","):"","",e,"&rt=",h.join(",")].join(""),b=new Image,j=window.GA_jstiming.i++;window.GA_jstiming.e[j]=b;b.onload=b.onerror=function(){delete window.GA_jstiming.e[j]};b.src=a;b=g;return a}};var n=this,q=function(a,b){var c,e=b,d=a.split(".");c=c||n;!(d[0]in c)&&c.execScript&&c.execScript("var "+d[0]);for(var f;d.length&&(f=d.shift());)!d.length&&e!==void 0?c[f]=e:c=c[f]?c[f]:c[f]={}},s=function(a,b){function c(){}c.prototype=b.prototype;a.k=b.prototype;a.prototype=new c};var u=function(){var a="false",b=!1;if(a=="true")return!0;if(a=="false")return!1;return b},v=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,w=function(a,b){if(!a)return b;var c=a.match(v);return c?c[0]:b};var x,y="0",z=0,A=parseFloat(y),B=x=isNaN(A)||A>1||A<0?z:A;var aa=u();var C=function(){return w("","pubads.g.doubleclick.net")};var D=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var E,F,G,H,I=function(){return n.navigator?n.navigator.userAgent:g};H=G=F=E=!1;var J;if(J=I()){var ba=n.navigator;E=J.indexOf("Opera")==0;F=!E&&J.indexOf("MSIE")!=-1;G=!E&&J.indexOf("WebKit")!=-1;H=!E&&!G&&ba.product=="Gecko"}var ca=E,K=F,L=H,da=G,M;
a:{var N="",O;if(ca&&n.opera)var P=n.opera.version,N=typeof P=="function"?P():P;else if(L?O=/rv\:([^\);]+)(\)|;)/:K?O=/MSIE\s+([^\);]+)(\)|;)/:da&&(O=/WebKit\/(\S+)/),O)var Q=O.exec(I()),N=Q?Q[1]:"";if(K){var R,S=n.document;R=S?S.documentMode:void 0;if(R>parseFloat(N)){M=String(R);break a}}M=N}
var ea=M,T={},U=function(a){var b;if(!(b=T[a])){b=T;for(var c=a,e=a,d=0,a=String(ea).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(e).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(a.length,e.length),h=0;d==0&&h<f;h++){var o=a[h]||"",i=e[h]||"",p=RegExp("(\\d*)(\\D*)","g"),t=RegExp("(\\d*)(\\D*)","g");do{var j=p.exec(o)||["","",""],r=t.exec(i)||["","",""];if(j[0].length==0&&r[0].length==0)break;var d=j[1].length==0?0:parseInt(j[1],10),fa=r[1].length==0?0:parseInt(r[1],10),d=
D(d,fa)||D(j[2].length==0,r[2].length==0)||D(j[2],r[2])}while(d==0)}a=d;b=b[c]=a>=0}return b};!K||U("9");!L&&!K||K&&U("9")||L&&U("1.9.1");K&&U("9");w("","pagead2.googlesyndication.com");var ga=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(g,a[c],c,a)},V=function(a){return!!a&&(a.indexOf("?google_debug")>0||a.indexOf("&google_debug")>0)};var W=function(){this.c=[];this.a={};for(var a=0,b=arguments.length;a<b;++a)this.a[arguments[a]]=""};W.prototype.j=function(a){if(this.a.hasOwnProperty(a))return this.a[a];return""};W.prototype.geil=W.prototype.j;var ha=function(a){var b=[],c=function(a){a!=""&&b.push(a)};ga(a.a,c);if(a.c.length>0&&b.length>0)return a.c.join(",")+","+b.join(",");return a.c.join(",")+b.join(",")};function ia(a){var b="adsense";if(a&&typeof a=="string"&&a.length>0)if(b==g)a=g;else{var c=window.GS_googleServiceIds_[b];c==g&&(c=b=="adsense"?new X:new Y,window.GS_googleServiceIds_[b]=c);b:{for(b=0;b<c.b.length;b++)if(a==c.b[b])break b;c.b[c.b.length]=a}a=c}else a=g;return a}q("GS_googleAddAdSenseService",ia);function ja(){for(var a in window.GS_googleServiceIds_){var b=window.GS_googleServiceIds_[a];typeof b!="function"&&b.enable()}}q("GS_googleEnableAllServices",ja);
function ka(){window.GS_googleServiceIds_={}}q("GS_googleResetAllServices",ka);function la(){var a="adsense",a=a==g?g:window.GS_googleServiceIds_[a];return a=a==g?"":a.b.join()}q("GS_googleGetIdsForAdSenseService",la);function ma(a){return Z(a)}q("GS_googleFindService",ma);function na(){var a=Z("adsense");return a?ha(a.d):""}q("GS_googleGetExpIdsForAdSense",na);function $(a){this.g=a;this.b=[];this.d=new W}
$.prototype.toString=function(){for(var a="["+this.g+" ids: ",b=0;b<this.b.length;b++)b>0&&(a+=","),a+=this.b[b];a+="]";return a};var Z=function(a){return a=a==g?g:window.GS_googleServiceIds_[a]};function Y(){$.call(this,"unknown")}s(Y,$);Y.prototype.enable=function(){};function X(){$.call(this,"adsense");this.f=!1}s(X,$);
var oa=function(a,b){var c;c=a;var e=Z("adsense"),d;var f=e.d,e=["32942002"],h;h=d?f.a.hasOwnProperty(d)&&f.a[d]=="":!0;h&&!(Math.random()<1.0E-4)&&Math.random()<b?(h=Math.floor(Math.random()*e.length),e=e[h],e==""?d="":d?d=f.a.hasOwnProperty(d)?f.a[d]=e:"":(f.c.push(e),d=e)):d="";c=d==="32942002"||c&&(c.indexOf("?use_google_ads2")>0||c.indexOf("&use_google_ads2")>0)?!0:!1;if(c){if(V(a))return"google_ads_dbg2.js";return"google_ads2.js"}else{if(V(a))return"google_ads_dbg.js";return"google_ads.js"}};
X.prototype.enable=function(){if(!this.f){var a;a=oa(document.URL,B);var b="http://"+w("","partner.googleadservices.com");aa&&(b="https://"+w("","securepubads.g.doubleclick.net"));var c="",e;e=C();(e=e=="pubads.g.doubleclick.net")||(c="?prodhost="+C());a=b+"/gampad/"+a+c;b="script";document.write("<"+b+' src="'+a+'"><\/script>');this.f=!0;if(window.GA_jstiming&&window.GA_jstiming.Timer)window.GA_jstiming.load.name="load",window.GA_jstiming.load.tick("start")}};
window.GS_googleServiceIds_||(window.GS_googleServiceIds_={});})()
