/* Variables header for application - AppBuilder 2.01  */

/* 'base' Window link */
const int ABN_base = 0;
const int ABN_PtMyMenuButton = 1;
const int ABN_PtPasswordButton = 2;
const int ABN_PtHello_WorldButton = 3;

/* 'new' Window link */
const int ABN_new = 4;
const int ABN_Plus = 5;

/* 'Hello_World' Window link */
const int ABN_Hello_World = 6;

/* 'Menu' Menu link */
const int ABN_Menu = 7;
const int ABN_Command = 8;
const int ABN_Submenu = 9;
const int ABN_Toggle = 10;
const int ABN_ExclusiveToggle = 11;
const int ABN_Quit = 14;

